/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/BrandsResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



BrandsResponse::BrandsResponse()
{
    m_BrandsIsSet = false;
    m_PaginationIsSet = false;
}

BrandsResponse::~BrandsResponse()
{
}

void BrandsResponse::validate()
{
    // TODO: implement validation
}

web::json::value BrandsResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_BrandsIsSet)
    {
        val[utility::conversions::to_string_t(U("brands"))] = ModelBase::toJson(m_Brands);
    }
    if(m_PaginationIsSet)
    {
        val[utility::conversions::to_string_t(U("pagination"))] = ModelBase::toJson(m_Pagination);
    }

    return val;
}

bool BrandsResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("brands"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("brands")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<VintedBrand>> refVal_setBrands;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBrands);
            setBrands(refVal_setBrands);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("pagination"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("pagination")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<VintedPagination> refVal_setPagination;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPagination);
            setPagination(refVal_setPagination);
        }
    }
    return ok;
}

void BrandsResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_BrandsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("brands")), m_Brands));
    }
    if(m_PaginationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("pagination")), m_Pagination));
    }
}

bool BrandsResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("brands"))))
    {
        std::vector<std::shared_ptr<VintedBrand>> refVal_setBrands;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("brands"))), refVal_setBrands );
        setBrands(refVal_setBrands);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("pagination"))))
    {
        std::shared_ptr<VintedPagination> refVal_setPagination;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("pagination"))), refVal_setPagination );
        setPagination(refVal_setPagination);
    }
    return ok;
}

std::vector<std::shared_ptr<VintedBrand>>& BrandsResponse::getBrands()
{
    return m_Brands;
}

void BrandsResponse::setBrands(const std::vector<std::shared_ptr<VintedBrand>>& value)
{
    m_Brands = value;
    m_BrandsIsSet = true;
}

bool BrandsResponse::brandsIsSet() const
{
    return m_BrandsIsSet;
}

void BrandsResponse::unsetBrands()
{
    m_BrandsIsSet = false;
}
std::shared_ptr<VintedPagination> BrandsResponse::getPagination() const
{
    return m_Pagination;
}

void BrandsResponse::setPagination(const std::shared_ptr<VintedPagination>& value)
{
    m_Pagination = value;
    m_PaginationIsSet = true;
}

bool BrandsResponse::paginationIsSet() const
{
    return m_PaginationIsSet;
}

void BrandsResponse::unsetPagination()
{
    m_PaginationIsSet = false;
}
}
}
}
}


