/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/StatusesResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



StatusesResponse::StatusesResponse()
{
    m_StatusesIsSet = false;
}

StatusesResponse::~StatusesResponse()
{
}

void StatusesResponse::validate()
{
    // TODO: implement validation
}

web::json::value StatusesResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_StatusesIsSet)
    {
        val[utility::conversions::to_string_t(U("statuses"))] = ModelBase::toJson(m_Statuses);
    }

    return val;
}

bool StatusesResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("statuses"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("statuses")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<VintedStatus>> refVal_setStatuses;
            ok &= ModelBase::fromJson(fieldValue, refVal_setStatuses);
            setStatuses(refVal_setStatuses);
        }
    }
    return ok;
}

void StatusesResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_StatusesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("statuses")), m_Statuses));
    }
}

bool StatusesResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("statuses"))))
    {
        std::vector<std::shared_ptr<VintedStatus>> refVal_setStatuses;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("statuses"))), refVal_setStatuses );
        setStatuses(refVal_setStatuses);
    }
    return ok;
}

std::vector<std::shared_ptr<VintedStatus>>& StatusesResponse::getStatuses()
{
    return m_Statuses;
}

void StatusesResponse::setStatuses(const std::vector<std::shared_ptr<VintedStatus>>& value)
{
    m_Statuses = value;
    m_StatusesIsSet = true;
}

bool StatusesResponse::statusesIsSet() const
{
    return m_StatusesIsSet;
}

void StatusesResponse::unsetStatuses()
{
    m_StatusesIsSet = false;
}
}
}
}
}


