/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/StreamMonitorListResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



StreamMonitorListResponse::StreamMonitorListResponse()
{
    m_MonitorsIsSet = false;
    m_Total = 0;
    m_TotalIsSet = false;
    m_Page = 0;
    m_PageIsSet = false;
    m_Page_size = 0;
    m_Page_sizeIsSet = false;
}

StreamMonitorListResponse::~StreamMonitorListResponse()
{
}

void StreamMonitorListResponse::validate()
{
    // TODO: implement validation
}

web::json::value StreamMonitorListResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_MonitorsIsSet)
    {
        val[utility::conversions::to_string_t(U("monitors"))] = ModelBase::toJson(m_Monitors);
    }
    if(m_TotalIsSet)
    {
        val[utility::conversions::to_string_t(U("total"))] = ModelBase::toJson(m_Total);
    }
    if(m_PageIsSet)
    {
        val[utility::conversions::to_string_t(U("page"))] = ModelBase::toJson(m_Page);
    }
    if(m_Page_sizeIsSet)
    {
        val[utility::conversions::to_string_t(U("page_size"))] = ModelBase::toJson(m_Page_size);
    }

    return val;
}

bool StreamMonitorListResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("monitors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("monitors")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<StreamMonitorResponse>> refVal_setMonitors;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMonitors);
            setMonitors(refVal_setMonitors);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotal);
            setTotal(refVal_setTotal);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("page"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("page")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPage);
            setPage(refVal_setPage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("page_size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("page_size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPageSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPageSize);
            setPageSize(refVal_setPageSize);
        }
    }
    return ok;
}

void StreamMonitorListResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_MonitorsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("monitors")), m_Monitors));
    }
    if(m_TotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total")), m_Total));
    }
    if(m_PageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("page")), m_Page));
    }
    if(m_Page_sizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("page_size")), m_Page_size));
    }
}

bool StreamMonitorListResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("monitors"))))
    {
        std::vector<std::shared_ptr<StreamMonitorResponse>> refVal_setMonitors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("monitors"))), refVal_setMonitors );
        setMonitors(refVal_setMonitors);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total"))))
    {
        int32_t refVal_setTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total"))), refVal_setTotal );
        setTotal(refVal_setTotal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("page"))))
    {
        int32_t refVal_setPage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("page"))), refVal_setPage );
        setPage(refVal_setPage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("page_size"))))
    {
        int32_t refVal_setPageSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("page_size"))), refVal_setPageSize );
        setPageSize(refVal_setPageSize);
    }
    return ok;
}

std::vector<std::shared_ptr<StreamMonitorResponse>>& StreamMonitorListResponse::getMonitors()
{
    return m_Monitors;
}

void StreamMonitorListResponse::setMonitors(const std::vector<std::shared_ptr<StreamMonitorResponse>>& value)
{
    m_Monitors = value;
    m_MonitorsIsSet = true;
}

bool StreamMonitorListResponse::monitorsIsSet() const
{
    return m_MonitorsIsSet;
}

void StreamMonitorListResponse::unsetMonitors()
{
    m_MonitorsIsSet = false;
}
int32_t StreamMonitorListResponse::getTotal() const
{
    return m_Total;
}

void StreamMonitorListResponse::setTotal(int32_t value)
{
    m_Total = value;
    m_TotalIsSet = true;
}

bool StreamMonitorListResponse::totalIsSet() const
{
    return m_TotalIsSet;
}

void StreamMonitorListResponse::unsetTotal()
{
    m_TotalIsSet = false;
}
int32_t StreamMonitorListResponse::getPage() const
{
    return m_Page;
}

void StreamMonitorListResponse::setPage(int32_t value)
{
    m_Page = value;
    m_PageIsSet = true;
}

bool StreamMonitorListResponse::pageIsSet() const
{
    return m_PageIsSet;
}

void StreamMonitorListResponse::unsetPage()
{
    m_PageIsSet = false;
}
int32_t StreamMonitorListResponse::getPageSize() const
{
    return m_Page_size;
}

void StreamMonitorListResponse::setPageSize(int32_t value)
{
    m_Page_size = value;
    m_Page_sizeIsSet = true;
}

bool StreamMonitorListResponse::pageSizeIsSet() const
{
    return m_Page_sizeIsSet;
}

void StreamMonitorListResponse::unsetPage_size()
{
    m_Page_sizeIsSet = false;
}
}
}
}
}


