/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/TweetDeliveryLogResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



TweetDeliveryLogResponse::TweetDeliveryLogResponse()
{
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Monitor_id = utility::conversions::to_string_t("");
    m_Monitor_idIsSet = false;
    m_Monitor_name = utility::conversions::to_string_t("");
    m_Monitor_nameIsSet = false;
    m_Tweet_id = utility::conversions::to_string_t("");
    m_Tweet_idIsSet = false;
    m_Author_username = utility::conversions::to_string_t("");
    m_Author_usernameIsSet = false;
    m_Tweet_text_preview = utility::conversions::to_string_t("");
    m_Tweet_text_previewIsSet = false;
    m_Tweet_url = utility::conversions::to_string_t("");
    m_Tweet_urlIsSet = false;
    m_Tweet_published_at = utility::datetime();
    m_Tweet_published_atIsSet = false;
    m_Detected_at = utility::datetime();
    m_Detected_atIsSet = false;
    m_Latency_ms = 0;
    m_Latency_msIsSet = false;
    m_Latency_badge = utility::conversions::to_string_t("");
    m_Latency_badgeIsSet = false;
    m_Delivery_status = utility::conversions::to_string_t("");
    m_Delivery_statusIsSet = false;
    m_Webhook_status_code = 0;
    m_Webhook_status_codeIsSet = false;
    m_Webhook_attempts = 0;
    m_Webhook_attemptsIsSet = false;
}

TweetDeliveryLogResponse::~TweetDeliveryLogResponse()
{
}

void TweetDeliveryLogResponse::validate()
{
    // TODO: implement validation
}

web::json::value TweetDeliveryLogResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_Monitor_idIsSet)
    {
        val[utility::conversions::to_string_t(U("monitor_id"))] = ModelBase::toJson(m_Monitor_id);
    }
    if(m_Monitor_nameIsSet)
    {
        val[utility::conversions::to_string_t(U("monitor_name"))] = ModelBase::toJson(m_Monitor_name);
    }
    if(m_Tweet_idIsSet)
    {
        val[utility::conversions::to_string_t(U("tweet_id"))] = ModelBase::toJson(m_Tweet_id);
    }
    if(m_Author_usernameIsSet)
    {
        val[utility::conversions::to_string_t(U("author_username"))] = ModelBase::toJson(m_Author_username);
    }
    if(m_Tweet_text_previewIsSet)
    {
        val[utility::conversions::to_string_t(U("tweet_text_preview"))] = ModelBase::toJson(m_Tweet_text_preview);
    }
    if(m_Tweet_urlIsSet)
    {
        val[utility::conversions::to_string_t(U("tweet_url"))] = ModelBase::toJson(m_Tweet_url);
    }
    if(m_Tweet_published_atIsSet)
    {
        val[utility::conversions::to_string_t(U("tweet_published_at"))] = ModelBase::toJson(m_Tweet_published_at);
    }
    if(m_Detected_atIsSet)
    {
        val[utility::conversions::to_string_t(U("detected_at"))] = ModelBase::toJson(m_Detected_at);
    }
    if(m_Latency_msIsSet)
    {
        val[utility::conversions::to_string_t(U("latency_ms"))] = ModelBase::toJson(m_Latency_ms);
    }
    if(m_Latency_badgeIsSet)
    {
        val[utility::conversions::to_string_t(U("latency_badge"))] = ModelBase::toJson(m_Latency_badge);
    }
    if(m_Delivery_statusIsSet)
    {
        val[utility::conversions::to_string_t(U("delivery_status"))] = ModelBase::toJson(m_Delivery_status);
    }
    if(m_Webhook_status_codeIsSet)
    {
        val[utility::conversions::to_string_t(U("webhook_status_code"))] = ModelBase::toJson(m_Webhook_status_code);
    }
    if(m_Webhook_attemptsIsSet)
    {
        val[utility::conversions::to_string_t(U("webhook_attempts"))] = ModelBase::toJson(m_Webhook_attempts);
    }

    return val;
}

bool TweetDeliveryLogResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("monitor_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("monitor_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMonitorId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMonitorId);
            setMonitorId(refVal_setMonitorId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("monitor_name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("monitor_name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setMonitorName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMonitorName);
            setMonitorName(refVal_setMonitorName);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tweet_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tweet_id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTweetId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTweetId);
            setTweetId(refVal_setTweetId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("author_username"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("author_username")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setAuthorUsername;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAuthorUsername);
            setAuthorUsername(refVal_setAuthorUsername);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tweet_text_preview"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tweet_text_preview")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTweetTextPreview;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTweetTextPreview);
            setTweetTextPreview(refVal_setTweetTextPreview);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tweet_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tweet_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTweetUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTweetUrl);
            setTweetUrl(refVal_setTweetUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("tweet_published_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("tweet_published_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setTweetPublishedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTweetPublishedAt);
            setTweetPublishedAt(refVal_setTweetPublishedAt);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("detected_at"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("detected_at")));
        if(!fieldValue.is_null())
        {
            utility::datetime refVal_setDetectedAt;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDetectedAt);
            setDetectedAt(refVal_setDetectedAt);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("latency_ms"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("latency_ms")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setLatencyMs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLatencyMs);
            setLatencyMs(refVal_setLatencyMs);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("latency_badge"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("latency_badge")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLatencyBadge;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLatencyBadge);
            setLatencyBadge(refVal_setLatencyBadge);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("delivery_status"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("delivery_status")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDeliveryStatus;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDeliveryStatus);
            setDeliveryStatus(refVal_setDeliveryStatus);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("webhook_status_code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("webhook_status_code")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setWebhookStatusCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWebhookStatusCode);
            setWebhookStatusCode(refVal_setWebhookStatusCode);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("webhook_attempts"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("webhook_attempts")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setWebhookAttempts;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWebhookAttempts);
            setWebhookAttempts(refVal_setWebhookAttempts);
        }
    }
    return ok;
}

void TweetDeliveryLogResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_Monitor_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("monitor_id")), m_Monitor_id));
    }
    if(m_Monitor_nameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("monitor_name")), m_Monitor_name));
    }
    if(m_Tweet_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tweet_id")), m_Tweet_id));
    }
    if(m_Author_usernameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("author_username")), m_Author_username));
    }
    if(m_Tweet_text_previewIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tweet_text_preview")), m_Tweet_text_preview));
    }
    if(m_Tweet_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tweet_url")), m_Tweet_url));
    }
    if(m_Tweet_published_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("tweet_published_at")), m_Tweet_published_at));
    }
    if(m_Detected_atIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("detected_at")), m_Detected_at));
    }
    if(m_Latency_msIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("latency_ms")), m_Latency_ms));
    }
    if(m_Latency_badgeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("latency_badge")), m_Latency_badge));
    }
    if(m_Delivery_statusIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("delivery_status")), m_Delivery_status));
    }
    if(m_Webhook_status_codeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("webhook_status_code")), m_Webhook_status_code));
    }
    if(m_Webhook_attemptsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("webhook_attempts")), m_Webhook_attempts));
    }
}

bool TweetDeliveryLogResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("monitor_id"))))
    {
        utility::string_t refVal_setMonitorId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("monitor_id"))), refVal_setMonitorId );
        setMonitorId(refVal_setMonitorId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("monitor_name"))))
    {
        utility::string_t refVal_setMonitorName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("monitor_name"))), refVal_setMonitorName );
        setMonitorName(refVal_setMonitorName);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tweet_id"))))
    {
        utility::string_t refVal_setTweetId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tweet_id"))), refVal_setTweetId );
        setTweetId(refVal_setTweetId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("author_username"))))
    {
        utility::string_t refVal_setAuthorUsername;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("author_username"))), refVal_setAuthorUsername );
        setAuthorUsername(refVal_setAuthorUsername);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tweet_text_preview"))))
    {
        utility::string_t refVal_setTweetTextPreview;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tweet_text_preview"))), refVal_setTweetTextPreview );
        setTweetTextPreview(refVal_setTweetTextPreview);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tweet_url"))))
    {
        utility::string_t refVal_setTweetUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tweet_url"))), refVal_setTweetUrl );
        setTweetUrl(refVal_setTweetUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("tweet_published_at"))))
    {
        utility::datetime refVal_setTweetPublishedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("tweet_published_at"))), refVal_setTweetPublishedAt );
        setTweetPublishedAt(refVal_setTweetPublishedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("detected_at"))))
    {
        utility::datetime refVal_setDetectedAt;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("detected_at"))), refVal_setDetectedAt );
        setDetectedAt(refVal_setDetectedAt);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("latency_ms"))))
    {
        int32_t refVal_setLatencyMs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("latency_ms"))), refVal_setLatencyMs );
        setLatencyMs(refVal_setLatencyMs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("latency_badge"))))
    {
        utility::string_t refVal_setLatencyBadge;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("latency_badge"))), refVal_setLatencyBadge );
        setLatencyBadge(refVal_setLatencyBadge);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("delivery_status"))))
    {
        utility::string_t refVal_setDeliveryStatus;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("delivery_status"))), refVal_setDeliveryStatus );
        setDeliveryStatus(refVal_setDeliveryStatus);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("webhook_status_code"))))
    {
        int32_t refVal_setWebhookStatusCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("webhook_status_code"))), refVal_setWebhookStatusCode );
        setWebhookStatusCode(refVal_setWebhookStatusCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("webhook_attempts"))))
    {
        int32_t refVal_setWebhookAttempts;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("webhook_attempts"))), refVal_setWebhookAttempts );
        setWebhookAttempts(refVal_setWebhookAttempts);
    }
    return ok;
}

utility::string_t TweetDeliveryLogResponse::getId() const
{
    return m_Id;
}

void TweetDeliveryLogResponse::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool TweetDeliveryLogResponse::idIsSet() const
{
    return m_IdIsSet;
}

void TweetDeliveryLogResponse::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getMonitorId() const
{
    return m_Monitor_id;
}

void TweetDeliveryLogResponse::setMonitorId(const utility::string_t& value)
{
    m_Monitor_id = value;
    m_Monitor_idIsSet = true;
}

bool TweetDeliveryLogResponse::monitorIdIsSet() const
{
    return m_Monitor_idIsSet;
}

void TweetDeliveryLogResponse::unsetMonitor_id()
{
    m_Monitor_idIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getMonitorName() const
{
    return m_Monitor_name;
}

void TweetDeliveryLogResponse::setMonitorName(const utility::string_t& value)
{
    m_Monitor_name = value;
    m_Monitor_nameIsSet = true;
}

bool TweetDeliveryLogResponse::monitorNameIsSet() const
{
    return m_Monitor_nameIsSet;
}

void TweetDeliveryLogResponse::unsetMonitor_name()
{
    m_Monitor_nameIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getTweetId() const
{
    return m_Tweet_id;
}

void TweetDeliveryLogResponse::setTweetId(const utility::string_t& value)
{
    m_Tweet_id = value;
    m_Tweet_idIsSet = true;
}

bool TweetDeliveryLogResponse::tweetIdIsSet() const
{
    return m_Tweet_idIsSet;
}

void TweetDeliveryLogResponse::unsetTweet_id()
{
    m_Tweet_idIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getAuthorUsername() const
{
    return m_Author_username;
}

void TweetDeliveryLogResponse::setAuthorUsername(const utility::string_t& value)
{
    m_Author_username = value;
    m_Author_usernameIsSet = true;
}

bool TweetDeliveryLogResponse::authorUsernameIsSet() const
{
    return m_Author_usernameIsSet;
}

void TweetDeliveryLogResponse::unsetAuthor_username()
{
    m_Author_usernameIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getTweetTextPreview() const
{
    return m_Tweet_text_preview;
}

void TweetDeliveryLogResponse::setTweetTextPreview(const utility::string_t& value)
{
    m_Tweet_text_preview = value;
    m_Tweet_text_previewIsSet = true;
}

bool TweetDeliveryLogResponse::tweetTextPreviewIsSet() const
{
    return m_Tweet_text_previewIsSet;
}

void TweetDeliveryLogResponse::unsetTweet_text_preview()
{
    m_Tweet_text_previewIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getTweetUrl() const
{
    return m_Tweet_url;
}

void TweetDeliveryLogResponse::setTweetUrl(const utility::string_t& value)
{
    m_Tweet_url = value;
    m_Tweet_urlIsSet = true;
}

bool TweetDeliveryLogResponse::tweetUrlIsSet() const
{
    return m_Tweet_urlIsSet;
}

void TweetDeliveryLogResponse::unsetTweet_url()
{
    m_Tweet_urlIsSet = false;
}
utility::datetime TweetDeliveryLogResponse::getTweetPublishedAt() const
{
    return m_Tweet_published_at;
}

void TweetDeliveryLogResponse::setTweetPublishedAt(const utility::datetime& value)
{
    m_Tweet_published_at = value;
    m_Tweet_published_atIsSet = true;
}

bool TweetDeliveryLogResponse::tweetPublishedAtIsSet() const
{
    return m_Tweet_published_atIsSet;
}

void TweetDeliveryLogResponse::unsetTweet_published_at()
{
    m_Tweet_published_atIsSet = false;
}
utility::datetime TweetDeliveryLogResponse::getDetectedAt() const
{
    return m_Detected_at;
}

void TweetDeliveryLogResponse::setDetectedAt(const utility::datetime& value)
{
    m_Detected_at = value;
    m_Detected_atIsSet = true;
}

bool TweetDeliveryLogResponse::detectedAtIsSet() const
{
    return m_Detected_atIsSet;
}

void TweetDeliveryLogResponse::unsetDetected_at()
{
    m_Detected_atIsSet = false;
}
int32_t TweetDeliveryLogResponse::getLatencyMs() const
{
    return m_Latency_ms;
}

void TweetDeliveryLogResponse::setLatencyMs(int32_t value)
{
    m_Latency_ms = value;
    m_Latency_msIsSet = true;
}

bool TweetDeliveryLogResponse::latencyMsIsSet() const
{
    return m_Latency_msIsSet;
}

void TweetDeliveryLogResponse::unsetLatency_ms()
{
    m_Latency_msIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getLatencyBadge() const
{
    return m_Latency_badge;
}

void TweetDeliveryLogResponse::setLatencyBadge(const utility::string_t& value)
{
    m_Latency_badge = value;
    m_Latency_badgeIsSet = true;
}

bool TweetDeliveryLogResponse::latencyBadgeIsSet() const
{
    return m_Latency_badgeIsSet;
}

void TweetDeliveryLogResponse::unsetLatency_badge()
{
    m_Latency_badgeIsSet = false;
}
utility::string_t TweetDeliveryLogResponse::getDeliveryStatus() const
{
    return m_Delivery_status;
}

void TweetDeliveryLogResponse::setDeliveryStatus(const utility::string_t& value)
{
    m_Delivery_status = value;
    m_Delivery_statusIsSet = true;
}

bool TweetDeliveryLogResponse::deliveryStatusIsSet() const
{
    return m_Delivery_statusIsSet;
}

void TweetDeliveryLogResponse::unsetDelivery_status()
{
    m_Delivery_statusIsSet = false;
}
int32_t TweetDeliveryLogResponse::getWebhookStatusCode() const
{
    return m_Webhook_status_code;
}

void TweetDeliveryLogResponse::setWebhookStatusCode(int32_t value)
{
    m_Webhook_status_code = value;
    m_Webhook_status_codeIsSet = true;
}

bool TweetDeliveryLogResponse::webhookStatusCodeIsSet() const
{
    return m_Webhook_status_codeIsSet;
}

void TweetDeliveryLogResponse::unsetWebhook_status_code()
{
    m_Webhook_status_codeIsSet = false;
}
int32_t TweetDeliveryLogResponse::getWebhookAttempts() const
{
    return m_Webhook_attempts;
}

void TweetDeliveryLogResponse::setWebhookAttempts(int32_t value)
{
    m_Webhook_attempts = value;
    m_Webhook_attemptsIsSet = true;
}

bool TweetDeliveryLogResponse::webhookAttemptsIsSet() const
{
    return m_Webhook_attemptsIsSet;
}

void TweetDeliveryLogResponse::unsetWebhook_attempts()
{
    m_Webhook_attemptsIsSet = false;
}
}
}
}
}


