/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/TweetDeliveryLogListResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



TweetDeliveryLogListResponse::TweetDeliveryLogListResponse()
{
    m_LogsIsSet = false;
    m_Total = 0;
    m_TotalIsSet = false;
    m_Page = 0;
    m_PageIsSet = false;
    m_Page_size = 0;
    m_Page_sizeIsSet = false;
}

TweetDeliveryLogListResponse::~TweetDeliveryLogListResponse()
{
}

void TweetDeliveryLogListResponse::validate()
{
    // TODO: implement validation
}

web::json::value TweetDeliveryLogListResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_LogsIsSet)
    {
        val[utility::conversions::to_string_t(U("logs"))] = ModelBase::toJson(m_Logs);
    }
    if(m_TotalIsSet)
    {
        val[utility::conversions::to_string_t(U("total"))] = ModelBase::toJson(m_Total);
    }
    if(m_PageIsSet)
    {
        val[utility::conversions::to_string_t(U("page"))] = ModelBase::toJson(m_Page);
    }
    if(m_Page_sizeIsSet)
    {
        val[utility::conversions::to_string_t(U("page_size"))] = ModelBase::toJson(m_Page_size);
    }

    return val;
}

bool TweetDeliveryLogListResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("logs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("logs")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<TweetDeliveryLogResponse>> refVal_setLogs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogs);
            setLogs(refVal_setLogs);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotal);
            setTotal(refVal_setTotal);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("page"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("page")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPage);
            setPage(refVal_setPage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("page_size"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("page_size")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPageSize;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPageSize);
            setPageSize(refVal_setPageSize);
        }
    }
    return ok;
}

void TweetDeliveryLogListResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_LogsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("logs")), m_Logs));
    }
    if(m_TotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total")), m_Total));
    }
    if(m_PageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("page")), m_Page));
    }
    if(m_Page_sizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("page_size")), m_Page_size));
    }
}

bool TweetDeliveryLogListResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("logs"))))
    {
        std::vector<std::shared_ptr<TweetDeliveryLogResponse>> refVal_setLogs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("logs"))), refVal_setLogs );
        setLogs(refVal_setLogs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total"))))
    {
        int32_t refVal_setTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total"))), refVal_setTotal );
        setTotal(refVal_setTotal);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("page"))))
    {
        int32_t refVal_setPage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("page"))), refVal_setPage );
        setPage(refVal_setPage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("page_size"))))
    {
        int32_t refVal_setPageSize;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("page_size"))), refVal_setPageSize );
        setPageSize(refVal_setPageSize);
    }
    return ok;
}

std::vector<std::shared_ptr<TweetDeliveryLogResponse>>& TweetDeliveryLogListResponse::getLogs()
{
    return m_Logs;
}

void TweetDeliveryLogListResponse::setLogs(const std::vector<std::shared_ptr<TweetDeliveryLogResponse>>& value)
{
    m_Logs = value;
    m_LogsIsSet = true;
}

bool TweetDeliveryLogListResponse::logsIsSet() const
{
    return m_LogsIsSet;
}

void TweetDeliveryLogListResponse::unsetLogs()
{
    m_LogsIsSet = false;
}
int32_t TweetDeliveryLogListResponse::getTotal() const
{
    return m_Total;
}

void TweetDeliveryLogListResponse::setTotal(int32_t value)
{
    m_Total = value;
    m_TotalIsSet = true;
}

bool TweetDeliveryLogListResponse::totalIsSet() const
{
    return m_TotalIsSet;
}

void TweetDeliveryLogListResponse::unsetTotal()
{
    m_TotalIsSet = false;
}
int32_t TweetDeliveryLogListResponse::getPage() const
{
    return m_Page;
}

void TweetDeliveryLogListResponse::setPage(int32_t value)
{
    m_Page = value;
    m_PageIsSet = true;
}

bool TweetDeliveryLogListResponse::pageIsSet() const
{
    return m_PageIsSet;
}

void TweetDeliveryLogListResponse::unsetPage()
{
    m_PageIsSet = false;
}
int32_t TweetDeliveryLogListResponse::getPageSize() const
{
    return m_Page_size;
}

void TweetDeliveryLogListResponse::setPageSize(int32_t value)
{
    m_Page_size = value;
    m_Page_sizeIsSet = true;
}

bool TweetDeliveryLogListResponse::pageSizeIsSet() const
{
    return m_Page_sizeIsSet;
}

void TweetDeliveryLogListResponse::unsetPage_size()
{
    m_Page_sizeIsSet = false;
}
}
}
}
}


