/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/VintedUserProfile.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



VintedUserProfile::VintedUserProfile()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Login = utility::conversions::to_string_t("");
    m_LoginIsSet = false;
    m_Photo_url = utility::conversions::to_string_t("");
    m_Photo_urlIsSet = false;
    m_Business = false;
    m_BusinessIsSet = false;
    m_Country_code = utility::conversions::to_string_t("");
    m_Country_codeIsSet = false;
    m_City = utility::conversions::to_string_t("");
    m_CityIsSet = false;
    m_Feedback_count = 0;
    m_Feedback_countIsSet = false;
    m_Feedback_reputation = 0.0;
    m_Feedback_reputationIsSet = false;
    m_Positive_feedback_count = 0;
    m_Positive_feedback_countIsSet = false;
    m_Neutral_feedback_count = 0;
    m_Neutral_feedback_countIsSet = false;
    m_Negative_feedback_count = 0;
    m_Negative_feedback_countIsSet = false;
    m_Item_count = 0;
    m_Item_countIsSet = false;
    m_Total_items_count = 0;
    m_Total_items_countIsSet = false;
    m_Followers_count = 0;
    m_Followers_countIsSet = false;
    m_Following_count = 0;
    m_Following_countIsSet = false;
    m_Is_online = false;
    m_Is_onlineIsSet = false;
    m_Is_on_holiday = false;
    m_Is_on_holidayIsSet = false;
    m_Last_loged_on_ts = utility::conversions::to_string_t("");
    m_Last_loged_on_tsIsSet = false;
    m_Profile_url = utility::conversions::to_string_t("");
    m_Profile_urlIsSet = false;
    m_Locale = utility::conversions::to_string_t("");
    m_LocaleIsSet = false;
}

VintedUserProfile::~VintedUserProfile()
{
}

void VintedUserProfile::validate()
{
    // TODO: implement validation
}

web::json::value VintedUserProfile::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_LoginIsSet)
    {
        val[utility::conversions::to_string_t(U("login"))] = ModelBase::toJson(m_Login);
    }
    if(m_Photo_urlIsSet)
    {
        val[utility::conversions::to_string_t(U("photo_url"))] = ModelBase::toJson(m_Photo_url);
    }
    if(m_BusinessIsSet)
    {
        val[utility::conversions::to_string_t(U("business"))] = ModelBase::toJson(m_Business);
    }
    if(m_Country_codeIsSet)
    {
        val[utility::conversions::to_string_t(U("country_code"))] = ModelBase::toJson(m_Country_code);
    }
    if(m_CityIsSet)
    {
        val[utility::conversions::to_string_t(U("city"))] = ModelBase::toJson(m_City);
    }
    if(m_Feedback_countIsSet)
    {
        val[utility::conversions::to_string_t(U("feedback_count"))] = ModelBase::toJson(m_Feedback_count);
    }
    if(m_Feedback_reputationIsSet)
    {
        val[utility::conversions::to_string_t(U("feedback_reputation"))] = ModelBase::toJson(m_Feedback_reputation);
    }
    if(m_Positive_feedback_countIsSet)
    {
        val[utility::conversions::to_string_t(U("positive_feedback_count"))] = ModelBase::toJson(m_Positive_feedback_count);
    }
    if(m_Neutral_feedback_countIsSet)
    {
        val[utility::conversions::to_string_t(U("neutral_feedback_count"))] = ModelBase::toJson(m_Neutral_feedback_count);
    }
    if(m_Negative_feedback_countIsSet)
    {
        val[utility::conversions::to_string_t(U("negative_feedback_count"))] = ModelBase::toJson(m_Negative_feedback_count);
    }
    if(m_Item_countIsSet)
    {
        val[utility::conversions::to_string_t(U("item_count"))] = ModelBase::toJson(m_Item_count);
    }
    if(m_Total_items_countIsSet)
    {
        val[utility::conversions::to_string_t(U("total_items_count"))] = ModelBase::toJson(m_Total_items_count);
    }
    if(m_Followers_countIsSet)
    {
        val[utility::conversions::to_string_t(U("followers_count"))] = ModelBase::toJson(m_Followers_count);
    }
    if(m_Following_countIsSet)
    {
        val[utility::conversions::to_string_t(U("following_count"))] = ModelBase::toJson(m_Following_count);
    }
    if(m_Is_onlineIsSet)
    {
        val[utility::conversions::to_string_t(U("is_online"))] = ModelBase::toJson(m_Is_online);
    }
    if(m_Is_on_holidayIsSet)
    {
        val[utility::conversions::to_string_t(U("is_on_holiday"))] = ModelBase::toJson(m_Is_on_holiday);
    }
    if(m_Last_loged_on_tsIsSet)
    {
        val[utility::conversions::to_string_t(U("last_loged_on_ts"))] = ModelBase::toJson(m_Last_loged_on_ts);
    }
    if(m_Profile_urlIsSet)
    {
        val[utility::conversions::to_string_t(U("profile_url"))] = ModelBase::toJson(m_Profile_url);
    }
    if(m_LocaleIsSet)
    {
        val[utility::conversions::to_string_t(U("locale"))] = ModelBase::toJson(m_Locale);
    }

    return val;
}

bool VintedUserProfile::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("login"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("login")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLogin;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLogin);
            setLogin(refVal_setLogin);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("photo_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("photo_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setPhotoUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPhotoUrl);
            setPhotoUrl(refVal_setPhotoUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("business"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("business")));
        if(!fieldValue.is_null())
        {
            bool refVal_setBusiness;
            ok &= ModelBase::fromJson(fieldValue, refVal_setBusiness);
            setBusiness(refVal_setBusiness);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("country_code"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("country_code")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCountryCode;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCountryCode);
            setCountryCode(refVal_setCountryCode);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("city"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("city")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setCity;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCity);
            setCity(refVal_setCity);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("feedback_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("feedback_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFeedbackCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFeedbackCount);
            setFeedbackCount(refVal_setFeedbackCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("feedback_reputation"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("feedback_reputation")));
        if(!fieldValue.is_null())
        {
            double refVal_setFeedbackReputation;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFeedbackReputation);
            setFeedbackReputation(refVal_setFeedbackReputation);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("positive_feedback_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("positive_feedback_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPositiveFeedbackCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPositiveFeedbackCount);
            setPositiveFeedbackCount(refVal_setPositiveFeedbackCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("neutral_feedback_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("neutral_feedback_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setNeutralFeedbackCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNeutralFeedbackCount);
            setNeutralFeedbackCount(refVal_setNeutralFeedbackCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("negative_feedback_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("negative_feedback_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setNegativeFeedbackCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setNegativeFeedbackCount);
            setNegativeFeedbackCount(refVal_setNegativeFeedbackCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("item_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("item_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setItemCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setItemCount);
            setItemCount(refVal_setItemCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total_items_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total_items_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalItemsCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalItemsCount);
            setTotalItemsCount(refVal_setTotalItemsCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("followers_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("followers_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFollowersCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFollowersCount);
            setFollowersCount(refVal_setFollowersCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("following_count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("following_count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setFollowingCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFollowingCount);
            setFollowingCount(refVal_setFollowingCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("is_online"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("is_online")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsOnline;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsOnline);
            setIsOnline(refVal_setIsOnline);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("is_on_holiday"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("is_on_holiday")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsOnHoliday;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsOnHoliday);
            setIsOnHoliday(refVal_setIsOnHoliday);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("last_loged_on_ts"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("last_loged_on_ts")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLastLogedOnTs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLastLogedOnTs);
            setLastLogedOnTs(refVal_setLastLogedOnTs);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("profile_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("profile_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setProfileUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setProfileUrl);
            setProfileUrl(refVal_setProfileUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("locale"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("locale")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setLocale;
            ok &= ModelBase::fromJson(fieldValue, refVal_setLocale);
            setLocale(refVal_setLocale);
        }
    }
    return ok;
}

void VintedUserProfile::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_LoginIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("login")), m_Login));
    }
    if(m_Photo_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("photo_url")), m_Photo_url));
    }
    if(m_BusinessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("business")), m_Business));
    }
    if(m_Country_codeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("country_code")), m_Country_code));
    }
    if(m_CityIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("city")), m_City));
    }
    if(m_Feedback_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("feedback_count")), m_Feedback_count));
    }
    if(m_Feedback_reputationIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("feedback_reputation")), m_Feedback_reputation));
    }
    if(m_Positive_feedback_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("positive_feedback_count")), m_Positive_feedback_count));
    }
    if(m_Neutral_feedback_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("neutral_feedback_count")), m_Neutral_feedback_count));
    }
    if(m_Negative_feedback_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("negative_feedback_count")), m_Negative_feedback_count));
    }
    if(m_Item_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("item_count")), m_Item_count));
    }
    if(m_Total_items_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total_items_count")), m_Total_items_count));
    }
    if(m_Followers_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("followers_count")), m_Followers_count));
    }
    if(m_Following_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("following_count")), m_Following_count));
    }
    if(m_Is_onlineIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("is_online")), m_Is_online));
    }
    if(m_Is_on_holidayIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("is_on_holiday")), m_Is_on_holiday));
    }
    if(m_Last_loged_on_tsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("last_loged_on_ts")), m_Last_loged_on_ts));
    }
    if(m_Profile_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("profile_url")), m_Profile_url));
    }
    if(m_LocaleIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("locale")), m_Locale));
    }
}

bool VintedUserProfile::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("login"))))
    {
        utility::string_t refVal_setLogin;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("login"))), refVal_setLogin );
        setLogin(refVal_setLogin);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("photo_url"))))
    {
        utility::string_t refVal_setPhotoUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("photo_url"))), refVal_setPhotoUrl );
        setPhotoUrl(refVal_setPhotoUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("business"))))
    {
        bool refVal_setBusiness;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("business"))), refVal_setBusiness );
        setBusiness(refVal_setBusiness);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("country_code"))))
    {
        utility::string_t refVal_setCountryCode;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("country_code"))), refVal_setCountryCode );
        setCountryCode(refVal_setCountryCode);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("city"))))
    {
        utility::string_t refVal_setCity;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("city"))), refVal_setCity );
        setCity(refVal_setCity);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("feedback_count"))))
    {
        int32_t refVal_setFeedbackCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("feedback_count"))), refVal_setFeedbackCount );
        setFeedbackCount(refVal_setFeedbackCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("feedback_reputation"))))
    {
        double refVal_setFeedbackReputation;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("feedback_reputation"))), refVal_setFeedbackReputation );
        setFeedbackReputation(refVal_setFeedbackReputation);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("positive_feedback_count"))))
    {
        int32_t refVal_setPositiveFeedbackCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("positive_feedback_count"))), refVal_setPositiveFeedbackCount );
        setPositiveFeedbackCount(refVal_setPositiveFeedbackCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("neutral_feedback_count"))))
    {
        int32_t refVal_setNeutralFeedbackCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("neutral_feedback_count"))), refVal_setNeutralFeedbackCount );
        setNeutralFeedbackCount(refVal_setNeutralFeedbackCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("negative_feedback_count"))))
    {
        int32_t refVal_setNegativeFeedbackCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("negative_feedback_count"))), refVal_setNegativeFeedbackCount );
        setNegativeFeedbackCount(refVal_setNegativeFeedbackCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("item_count"))))
    {
        int32_t refVal_setItemCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("item_count"))), refVal_setItemCount );
        setItemCount(refVal_setItemCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total_items_count"))))
    {
        int32_t refVal_setTotalItemsCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total_items_count"))), refVal_setTotalItemsCount );
        setTotalItemsCount(refVal_setTotalItemsCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("followers_count"))))
    {
        int32_t refVal_setFollowersCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("followers_count"))), refVal_setFollowersCount );
        setFollowersCount(refVal_setFollowersCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("following_count"))))
    {
        int32_t refVal_setFollowingCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("following_count"))), refVal_setFollowingCount );
        setFollowingCount(refVal_setFollowingCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("is_online"))))
    {
        bool refVal_setIsOnline;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("is_online"))), refVal_setIsOnline );
        setIsOnline(refVal_setIsOnline);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("is_on_holiday"))))
    {
        bool refVal_setIsOnHoliday;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("is_on_holiday"))), refVal_setIsOnHoliday );
        setIsOnHoliday(refVal_setIsOnHoliday);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("last_loged_on_ts"))))
    {
        utility::string_t refVal_setLastLogedOnTs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("last_loged_on_ts"))), refVal_setLastLogedOnTs );
        setLastLogedOnTs(refVal_setLastLogedOnTs);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("profile_url"))))
    {
        utility::string_t refVal_setProfileUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("profile_url"))), refVal_setProfileUrl );
        setProfileUrl(refVal_setProfileUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("locale"))))
    {
        utility::string_t refVal_setLocale;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("locale"))), refVal_setLocale );
        setLocale(refVal_setLocale);
    }
    return ok;
}

int32_t VintedUserProfile::getId() const
{
    return m_Id;
}

void VintedUserProfile::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool VintedUserProfile::idIsSet() const
{
    return m_IdIsSet;
}

void VintedUserProfile::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t VintedUserProfile::getLogin() const
{
    return m_Login;
}

void VintedUserProfile::setLogin(const utility::string_t& value)
{
    m_Login = value;
    m_LoginIsSet = true;
}

bool VintedUserProfile::loginIsSet() const
{
    return m_LoginIsSet;
}

void VintedUserProfile::unsetLogin()
{
    m_LoginIsSet = false;
}
utility::string_t VintedUserProfile::getPhotoUrl() const
{
    return m_Photo_url;
}

void VintedUserProfile::setPhotoUrl(const utility::string_t& value)
{
    m_Photo_url = value;
    m_Photo_urlIsSet = true;
}

bool VintedUserProfile::photoUrlIsSet() const
{
    return m_Photo_urlIsSet;
}

void VintedUserProfile::unsetPhoto_url()
{
    m_Photo_urlIsSet = false;
}
bool VintedUserProfile::isBusiness() const
{
    return m_Business;
}

void VintedUserProfile::setBusiness(bool value)
{
    m_Business = value;
    m_BusinessIsSet = true;
}

bool VintedUserProfile::businessIsSet() const
{
    return m_BusinessIsSet;
}

void VintedUserProfile::unsetBusiness()
{
    m_BusinessIsSet = false;
}
utility::string_t VintedUserProfile::getCountryCode() const
{
    return m_Country_code;
}

void VintedUserProfile::setCountryCode(const utility::string_t& value)
{
    m_Country_code = value;
    m_Country_codeIsSet = true;
}

bool VintedUserProfile::countryCodeIsSet() const
{
    return m_Country_codeIsSet;
}

void VintedUserProfile::unsetCountry_code()
{
    m_Country_codeIsSet = false;
}
utility::string_t VintedUserProfile::getCity() const
{
    return m_City;
}

void VintedUserProfile::setCity(const utility::string_t& value)
{
    m_City = value;
    m_CityIsSet = true;
}

bool VintedUserProfile::cityIsSet() const
{
    return m_CityIsSet;
}

void VintedUserProfile::unsetCity()
{
    m_CityIsSet = false;
}
int32_t VintedUserProfile::getFeedbackCount() const
{
    return m_Feedback_count;
}

void VintedUserProfile::setFeedbackCount(int32_t value)
{
    m_Feedback_count = value;
    m_Feedback_countIsSet = true;
}

bool VintedUserProfile::feedbackCountIsSet() const
{
    return m_Feedback_countIsSet;
}

void VintedUserProfile::unsetFeedback_count()
{
    m_Feedback_countIsSet = false;
}
double VintedUserProfile::getFeedbackReputation() const
{
    return m_Feedback_reputation;
}

void VintedUserProfile::setFeedbackReputation(double value)
{
    m_Feedback_reputation = value;
    m_Feedback_reputationIsSet = true;
}

bool VintedUserProfile::feedbackReputationIsSet() const
{
    return m_Feedback_reputationIsSet;
}

void VintedUserProfile::unsetFeedback_reputation()
{
    m_Feedback_reputationIsSet = false;
}
int32_t VintedUserProfile::getPositiveFeedbackCount() const
{
    return m_Positive_feedback_count;
}

void VintedUserProfile::setPositiveFeedbackCount(int32_t value)
{
    m_Positive_feedback_count = value;
    m_Positive_feedback_countIsSet = true;
}

bool VintedUserProfile::positiveFeedbackCountIsSet() const
{
    return m_Positive_feedback_countIsSet;
}

void VintedUserProfile::unsetPositive_feedback_count()
{
    m_Positive_feedback_countIsSet = false;
}
int32_t VintedUserProfile::getNeutralFeedbackCount() const
{
    return m_Neutral_feedback_count;
}

void VintedUserProfile::setNeutralFeedbackCount(int32_t value)
{
    m_Neutral_feedback_count = value;
    m_Neutral_feedback_countIsSet = true;
}

bool VintedUserProfile::neutralFeedbackCountIsSet() const
{
    return m_Neutral_feedback_countIsSet;
}

void VintedUserProfile::unsetNeutral_feedback_count()
{
    m_Neutral_feedback_countIsSet = false;
}
int32_t VintedUserProfile::getNegativeFeedbackCount() const
{
    return m_Negative_feedback_count;
}

void VintedUserProfile::setNegativeFeedbackCount(int32_t value)
{
    m_Negative_feedback_count = value;
    m_Negative_feedback_countIsSet = true;
}

bool VintedUserProfile::negativeFeedbackCountIsSet() const
{
    return m_Negative_feedback_countIsSet;
}

void VintedUserProfile::unsetNegative_feedback_count()
{
    m_Negative_feedback_countIsSet = false;
}
int32_t VintedUserProfile::getItemCount() const
{
    return m_Item_count;
}

void VintedUserProfile::setItemCount(int32_t value)
{
    m_Item_count = value;
    m_Item_countIsSet = true;
}

bool VintedUserProfile::itemCountIsSet() const
{
    return m_Item_countIsSet;
}

void VintedUserProfile::unsetItem_count()
{
    m_Item_countIsSet = false;
}
int32_t VintedUserProfile::getTotalItemsCount() const
{
    return m_Total_items_count;
}

void VintedUserProfile::setTotalItemsCount(int32_t value)
{
    m_Total_items_count = value;
    m_Total_items_countIsSet = true;
}

bool VintedUserProfile::totalItemsCountIsSet() const
{
    return m_Total_items_countIsSet;
}

void VintedUserProfile::unsetTotal_items_count()
{
    m_Total_items_countIsSet = false;
}
int32_t VintedUserProfile::getFollowersCount() const
{
    return m_Followers_count;
}

void VintedUserProfile::setFollowersCount(int32_t value)
{
    m_Followers_count = value;
    m_Followers_countIsSet = true;
}

bool VintedUserProfile::followersCountIsSet() const
{
    return m_Followers_countIsSet;
}

void VintedUserProfile::unsetFollowers_count()
{
    m_Followers_countIsSet = false;
}
int32_t VintedUserProfile::getFollowingCount() const
{
    return m_Following_count;
}

void VintedUserProfile::setFollowingCount(int32_t value)
{
    m_Following_count = value;
    m_Following_countIsSet = true;
}

bool VintedUserProfile::followingCountIsSet() const
{
    return m_Following_countIsSet;
}

void VintedUserProfile::unsetFollowing_count()
{
    m_Following_countIsSet = false;
}
bool VintedUserProfile::isIsOnline() const
{
    return m_Is_online;
}

void VintedUserProfile::setIsOnline(bool value)
{
    m_Is_online = value;
    m_Is_onlineIsSet = true;
}

bool VintedUserProfile::isOnlineIsSet() const
{
    return m_Is_onlineIsSet;
}

void VintedUserProfile::unsetIs_online()
{
    m_Is_onlineIsSet = false;
}
bool VintedUserProfile::isIsOnHoliday() const
{
    return m_Is_on_holiday;
}

void VintedUserProfile::setIsOnHoliday(bool value)
{
    m_Is_on_holiday = value;
    m_Is_on_holidayIsSet = true;
}

bool VintedUserProfile::isOnHolidayIsSet() const
{
    return m_Is_on_holidayIsSet;
}

void VintedUserProfile::unsetIs_on_holiday()
{
    m_Is_on_holidayIsSet = false;
}
utility::string_t VintedUserProfile::getLastLogedOnTs() const
{
    return m_Last_loged_on_ts;
}

void VintedUserProfile::setLastLogedOnTs(const utility::string_t& value)
{
    m_Last_loged_on_ts = value;
    m_Last_loged_on_tsIsSet = true;
}

bool VintedUserProfile::lastLogedOnTsIsSet() const
{
    return m_Last_loged_on_tsIsSet;
}

void VintedUserProfile::unsetLast_loged_on_ts()
{
    m_Last_loged_on_tsIsSet = false;
}
utility::string_t VintedUserProfile::getProfileUrl() const
{
    return m_Profile_url;
}

void VintedUserProfile::setProfileUrl(const utility::string_t& value)
{
    m_Profile_url = value;
    m_Profile_urlIsSet = true;
}

bool VintedUserProfile::profileUrlIsSet() const
{
    return m_Profile_urlIsSet;
}

void VintedUserProfile::unsetProfile_url()
{
    m_Profile_urlIsSet = false;
}
utility::string_t VintedUserProfile::getLocale() const
{
    return m_Locale;
}

void VintedUserProfile::setLocale(const utility::string_t& value)
{
    m_Locale = value;
    m_LocaleIsSet = true;
}

bool VintedUserProfile::localeIsSet() const
{
    return m_LocaleIsSet;
}

void VintedUserProfile::unsetLocale()
{
    m_LocaleIsSet = false;
}
}
}
}
}


