/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/VintedPhoto.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



VintedPhoto::VintedPhoto()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Url = utility::conversions::to_string_t("");
    m_UrlIsSet = false;
    m_Dominant_color = utility::conversions::to_string_t("");
    m_Dominant_colorIsSet = false;
    m_Is_main = false;
    m_Is_mainIsSet = false;
    m_Width = 0;
    m_WidthIsSet = false;
    m_Height = 0;
    m_HeightIsSet = false;
    m_Full_size_url = utility::conversions::to_string_t("");
    m_Full_size_urlIsSet = false;
}

VintedPhoto::~VintedPhoto()
{
}

void VintedPhoto::validate()
{
    // TODO: implement validation
}

web::json::value VintedPhoto::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_UrlIsSet)
    {
        val[utility::conversions::to_string_t(U("url"))] = ModelBase::toJson(m_Url);
    }
    if(m_Dominant_colorIsSet)
    {
        val[utility::conversions::to_string_t(U("dominant_color"))] = ModelBase::toJson(m_Dominant_color);
    }
    if(m_Is_mainIsSet)
    {
        val[utility::conversions::to_string_t(U("is_main"))] = ModelBase::toJson(m_Is_main);
    }
    if(m_WidthIsSet)
    {
        val[utility::conversions::to_string_t(U("width"))] = ModelBase::toJson(m_Width);
    }
    if(m_HeightIsSet)
    {
        val[utility::conversions::to_string_t(U("height"))] = ModelBase::toJson(m_Height);
    }
    if(m_Full_size_urlIsSet)
    {
        val[utility::conversions::to_string_t(U("full_size_url"))] = ModelBase::toJson(m_Full_size_url);
    }

    return val;
}

bool VintedPhoto::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUrl);
            setUrl(refVal_setUrl);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("dominant_color"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("dominant_color")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setDominantColor;
            ok &= ModelBase::fromJson(fieldValue, refVal_setDominantColor);
            setDominantColor(refVal_setDominantColor);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("is_main"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("is_main")));
        if(!fieldValue.is_null())
        {
            bool refVal_setIsMain;
            ok &= ModelBase::fromJson(fieldValue, refVal_setIsMain);
            setIsMain(refVal_setIsMain);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("width"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("width")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setWidth;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWidth);
            setWidth(refVal_setWidth);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("height"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("height")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setHeight;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHeight);
            setHeight(refVal_setHeight);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("full_size_url"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("full_size_url")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setFullSizeUrl;
            ok &= ModelBase::fromJson(fieldValue, refVal_setFullSizeUrl);
            setFullSizeUrl(refVal_setFullSizeUrl);
        }
    }
    return ok;
}

void VintedPhoto::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_UrlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("url")), m_Url));
    }
    if(m_Dominant_colorIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("dominant_color")), m_Dominant_color));
    }
    if(m_Is_mainIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("is_main")), m_Is_main));
    }
    if(m_WidthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("width")), m_Width));
    }
    if(m_HeightIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("height")), m_Height));
    }
    if(m_Full_size_urlIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("full_size_url")), m_Full_size_url));
    }
}

bool VintedPhoto::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        int32_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("url"))))
    {
        utility::string_t refVal_setUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("url"))), refVal_setUrl );
        setUrl(refVal_setUrl);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("dominant_color"))))
    {
        utility::string_t refVal_setDominantColor;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("dominant_color"))), refVal_setDominantColor );
        setDominantColor(refVal_setDominantColor);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("is_main"))))
    {
        bool refVal_setIsMain;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("is_main"))), refVal_setIsMain );
        setIsMain(refVal_setIsMain);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("width"))))
    {
        int32_t refVal_setWidth;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("width"))), refVal_setWidth );
        setWidth(refVal_setWidth);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("height"))))
    {
        int32_t refVal_setHeight;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("height"))), refVal_setHeight );
        setHeight(refVal_setHeight);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("full_size_url"))))
    {
        utility::string_t refVal_setFullSizeUrl;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("full_size_url"))), refVal_setFullSizeUrl );
        setFullSizeUrl(refVal_setFullSizeUrl);
    }
    return ok;
}

int32_t VintedPhoto::getId() const
{
    return m_Id;
}

void VintedPhoto::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool VintedPhoto::idIsSet() const
{
    return m_IdIsSet;
}

void VintedPhoto::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t VintedPhoto::getUrl() const
{
    return m_Url;
}

void VintedPhoto::setUrl(const utility::string_t& value)
{
    m_Url = value;
    m_UrlIsSet = true;
}

bool VintedPhoto::urlIsSet() const
{
    return m_UrlIsSet;
}

void VintedPhoto::unsetUrl()
{
    m_UrlIsSet = false;
}
utility::string_t VintedPhoto::getDominantColor() const
{
    return m_Dominant_color;
}

void VintedPhoto::setDominantColor(const utility::string_t& value)
{
    m_Dominant_color = value;
    m_Dominant_colorIsSet = true;
}

bool VintedPhoto::dominantColorIsSet() const
{
    return m_Dominant_colorIsSet;
}

void VintedPhoto::unsetDominant_color()
{
    m_Dominant_colorIsSet = false;
}
bool VintedPhoto::isIsMain() const
{
    return m_Is_main;
}

void VintedPhoto::setIsMain(bool value)
{
    m_Is_main = value;
    m_Is_mainIsSet = true;
}

bool VintedPhoto::isMainIsSet() const
{
    return m_Is_mainIsSet;
}

void VintedPhoto::unsetIs_main()
{
    m_Is_mainIsSet = false;
}
int32_t VintedPhoto::getWidth() const
{
    return m_Width;
}

void VintedPhoto::setWidth(int32_t value)
{
    m_Width = value;
    m_WidthIsSet = true;
}

bool VintedPhoto::widthIsSet() const
{
    return m_WidthIsSet;
}

void VintedPhoto::unsetWidth()
{
    m_WidthIsSet = false;
}
int32_t VintedPhoto::getHeight() const
{
    return m_Height;
}

void VintedPhoto::setHeight(int32_t value)
{
    m_Height = value;
    m_HeightIsSet = true;
}

bool VintedPhoto::heightIsSet() const
{
    return m_HeightIsSet;
}

void VintedPhoto::unsetHeight()
{
    m_HeightIsSet = false;
}
utility::string_t VintedPhoto::getFullSizeUrl() const
{
    return m_Full_size_url;
}

void VintedPhoto::setFullSizeUrl(const utility::string_t& value)
{
    m_Full_size_url = value;
    m_Full_size_urlIsSet = true;
}

bool VintedPhoto::fullSizeUrlIsSet() const
{
    return m_Full_size_urlIsSet;
}

void VintedPhoto::unsetFull_size_url()
{
    m_Full_size_urlIsSet = false;
}
}
}
}
}


