/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/VintedPagination.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



VintedPagination::VintedPagination()
{
    m_Current_page = 0;
    m_Current_pageIsSet = false;
    m_Total_pages = 0;
    m_Total_pagesIsSet = false;
    m_Total_entries = 0;
    m_Total_entriesIsSet = false;
    m_Per_page = 0;
    m_Per_pageIsSet = false;
    m_Time = 0;
    m_TimeIsSet = false;
}

VintedPagination::~VintedPagination()
{
}

void VintedPagination::validate()
{
    // TODO: implement validation
}

web::json::value VintedPagination::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Current_pageIsSet)
    {
        val[utility::conversions::to_string_t(U("current_page"))] = ModelBase::toJson(m_Current_page);
    }
    if(m_Total_pagesIsSet)
    {
        val[utility::conversions::to_string_t(U("total_pages"))] = ModelBase::toJson(m_Total_pages);
    }
    if(m_Total_entriesIsSet)
    {
        val[utility::conversions::to_string_t(U("total_entries"))] = ModelBase::toJson(m_Total_entries);
    }
    if(m_Per_pageIsSet)
    {
        val[utility::conversions::to_string_t(U("per_page"))] = ModelBase::toJson(m_Per_page);
    }
    if(m_TimeIsSet)
    {
        val[utility::conversions::to_string_t(U("time"))] = ModelBase::toJson(m_Time);
    }

    return val;
}

bool VintedPagination::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("current_page"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("current_page")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCurrentPage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCurrentPage);
            setCurrentPage(refVal_setCurrentPage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total_pages"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total_pages")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalPages;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalPages);
            setTotalPages(refVal_setTotalPages);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total_entries"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total_entries")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalEntries;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalEntries);
            setTotalEntries(refVal_setTotalEntries);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("per_page"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("per_page")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setPerPage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPerPage);
            setPerPage(refVal_setPerPage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("time")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTime);
            setTime(refVal_setTime);
        }
    }
    return ok;
}

void VintedPagination::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Current_pageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("current_page")), m_Current_page));
    }
    if(m_Total_pagesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total_pages")), m_Total_pages));
    }
    if(m_Total_entriesIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total_entries")), m_Total_entries));
    }
    if(m_Per_pageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("per_page")), m_Per_page));
    }
    if(m_TimeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("time")), m_Time));
    }
}

bool VintedPagination::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("current_page"))))
    {
        int32_t refVal_setCurrentPage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("current_page"))), refVal_setCurrentPage );
        setCurrentPage(refVal_setCurrentPage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total_pages"))))
    {
        int32_t refVal_setTotalPages;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total_pages"))), refVal_setTotalPages );
        setTotalPages(refVal_setTotalPages);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total_entries"))))
    {
        int32_t refVal_setTotalEntries;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total_entries"))), refVal_setTotalEntries );
        setTotalEntries(refVal_setTotalEntries);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("per_page"))))
    {
        int32_t refVal_setPerPage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("per_page"))), refVal_setPerPage );
        setPerPage(refVal_setPerPage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("time"))))
    {
        int32_t refVal_setTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("time"))), refVal_setTime );
        setTime(refVal_setTime);
    }
    return ok;
}

int32_t VintedPagination::getCurrentPage() const
{
    return m_Current_page;
}

void VintedPagination::setCurrentPage(int32_t value)
{
    m_Current_page = value;
    m_Current_pageIsSet = true;
}

bool VintedPagination::currentPageIsSet() const
{
    return m_Current_pageIsSet;
}

void VintedPagination::unsetCurrent_page()
{
    m_Current_pageIsSet = false;
}
int32_t VintedPagination::getTotalPages() const
{
    return m_Total_pages;
}

void VintedPagination::setTotalPages(int32_t value)
{
    m_Total_pages = value;
    m_Total_pagesIsSet = true;
}

bool VintedPagination::totalPagesIsSet() const
{
    return m_Total_pagesIsSet;
}

void VintedPagination::unsetTotal_pages()
{
    m_Total_pagesIsSet = false;
}
int32_t VintedPagination::getTotalEntries() const
{
    return m_Total_entries;
}

void VintedPagination::setTotalEntries(int32_t value)
{
    m_Total_entries = value;
    m_Total_entriesIsSet = true;
}

bool VintedPagination::totalEntriesIsSet() const
{
    return m_Total_entriesIsSet;
}

void VintedPagination::unsetTotal_entries()
{
    m_Total_entriesIsSet = false;
}
int32_t VintedPagination::getPerPage() const
{
    return m_Per_page;
}

void VintedPagination::setPerPage(int32_t value)
{
    m_Per_page = value;
    m_Per_pageIsSet = true;
}

bool VintedPagination::perPageIsSet() const
{
    return m_Per_pageIsSet;
}

void VintedPagination::unsetPer_page()
{
    m_Per_pageIsSet = false;
}
int32_t VintedPagination::getTime() const
{
    return m_Time;
}

void VintedPagination::setTime(int32_t value)
{
    m_Time = value;
    m_TimeIsSet = true;
}

bool VintedPagination::timeIsSet() const
{
    return m_TimeIsSet;
}

void VintedPagination::unsetTime()
{
    m_TimeIsSet = false;
}
}
}
}
}


