/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "scrapebadger/model/WebhookListResponse.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



WebhookListResponse::WebhookListResponse()
{
    m_WebhooksIsSet = false;
    m_Total = 0;
    m_TotalIsSet = false;
}

WebhookListResponse::~WebhookListResponse()
{
}

void WebhookListResponse::validate()
{
    // TODO: implement validation
}

web::json::value WebhookListResponse::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_WebhooksIsSet)
    {
        val[utility::conversions::to_string_t(U("webhooks"))] = ModelBase::toJson(m_Webhooks);
    }
    if(m_TotalIsSet)
    {
        val[utility::conversions::to_string_t(U("total"))] = ModelBase::toJson(m_Total);
    }

    return val;
}

bool WebhookListResponse::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("webhooks"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("webhooks")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<WebhookListItem>> refVal_setWebhooks;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWebhooks);
            setWebhooks(refVal_setWebhooks);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotal);
            setTotal(refVal_setTotal);
        }
    }
    return ok;
}

void WebhookListResponse::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_WebhooksIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("webhooks")), m_Webhooks));
    }
    if(m_TotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total")), m_Total));
    }
}

bool WebhookListResponse::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("webhooks"))))
    {
        std::vector<std::shared_ptr<WebhookListItem>> refVal_setWebhooks;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("webhooks"))), refVal_setWebhooks );
        setWebhooks(refVal_setWebhooks);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total"))))
    {
        int32_t refVal_setTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total"))), refVal_setTotal );
        setTotal(refVal_setTotal);
    }
    return ok;
}

std::vector<std::shared_ptr<WebhookListItem>>& WebhookListResponse::getWebhooks()
{
    return m_Webhooks;
}

void WebhookListResponse::setWebhooks(const std::vector<std::shared_ptr<WebhookListItem>>& value)
{
    m_Webhooks = value;
    m_WebhooksIsSet = true;
}

bool WebhookListResponse::webhooksIsSet() const
{
    return m_WebhooksIsSet;
}

void WebhookListResponse::unsetWebhooks()
{
    m_WebhooksIsSet = false;
}
int32_t WebhookListResponse::getTotal() const
{
    return m_Total;
}

void WebhookListResponse::setTotal(int32_t value)
{
    m_Total = value;
    m_TotalIsSet = true;
}

bool WebhookListResponse::totalIsSet() const
{
    return m_TotalIsSet;
}

void WebhookListResponse::unsetTotal()
{
    m_TotalIsSet = false;
}
}
}
}
}


