/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BillingLogResponse.h
 *
 * Billing activity log entry.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BillingLogResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BillingLogResponse_H_


#include "scrapebadger/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Billing activity log entry.
/// </summary>
class  BillingLogResponse
    : public ModelBase
{
public:
    BillingLogResponse();
    virtual ~BillingLogResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BillingLogResponse members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMonitorId() const;
    bool monitorIdIsSet() const;
    void unsetMonitor_id();

    void setMonitorId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMonitorName() const;
    bool monitorNameIsSet() const;
    void unsetMonitor_name();

    void setMonitorName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getBilledAt() const;
    bool billedAtIsSet() const;
    void unsetBilled_at();

    void setBilledAt(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getNumAccounts() const;
    bool numAccountsIsSet() const;
    void unsetNum_accounts();

    void setNumAccounts(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    double getCreditsDeducted() const;
    bool creditsDeductedIsSet() const;
    void unsetCredits_deducted();

    void setCreditsDeducted(double value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTierLabel() const;
    bool tierLabelIsSet() const;
    void unsetTier_label();

    void setTierLabel(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getRateApplied() const;
    bool rateAppliedIsSet() const;
    void unsetRate_applied();

    void setRateApplied(double value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_Monitor_id;
    bool m_Monitor_idIsSet;
    utility::string_t m_Monitor_name;
    bool m_Monitor_nameIsSet;
    utility::datetime m_Billed_at;
    bool m_Billed_atIsSet;
    int32_t m_Num_accounts;
    bool m_Num_accountsIsSet;
    double m_Credits_deducted;
    bool m_Credits_deductedIsSet;
    utility::string_t m_Tier_label;
    bool m_Tier_labelIsSet;
    double m_Rate_applied;
    bool m_Rate_appliedIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BillingLogResponse_H_ */
