/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BrandsResponse.h
 *
 * Envelope returned by brand search.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_BrandsResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_BrandsResponse_H_


#include "scrapebadger/ModelBase.h"

#include "scrapebadger/model/VintedBrand.h"
#include "scrapebadger/model/VintedPagination.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class VintedBrand;
class VintedPagination;


/// <summary>
/// Envelope returned by brand search.
/// </summary>
class  BrandsResponse
    : public ModelBase
{
public:
    BrandsResponse();
    virtual ~BrandsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// BrandsResponse members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<VintedBrand>>& getBrands();
    bool brandsIsSet() const;
    void unsetBrands();

    void setBrands(const std::vector<std::shared_ptr<VintedBrand>>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VintedPagination> getPagination() const;
    bool paginationIsSet() const;
    void unsetPagination();

    void setPagination(const std::shared_ptr<VintedPagination>& value);


protected:
    std::vector<std::shared_ptr<VintedBrand>> m_Brands;
    bool m_BrandsIsSet;
    std::shared_ptr<VintedPagination> m_Pagination;
    bool m_PaginationIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_BrandsResponse_H_ */
