/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FilterRuleUpdate.h
 *
 * Partial update filter rule request.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleUpdate_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleUpdate_H_


#include "scrapebadger/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Partial update filter rule request.
/// </summary>
class  FilterRuleUpdate
    : public ModelBase
{
public:
    FilterRuleUpdate();
    virtual ~FilterRuleUpdate();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FilterRuleUpdate members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTag() const;
    bool tagIsSet() const;
    void unsetTag();

    void setTag(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getQuery() const;
    bool queryIsSet() const;
    void unsetQuery();

    void setQuery(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getIntervalSeconds() const;
    bool intervalSecondsIsSet() const;
    void unsetInterval_seconds();

    void setIntervalSeconds(double value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getMaxResultsPerPoll() const;
    bool maxResultsPerPollIsSet() const;
    void unsetMax_results_per_poll();

    void setMaxResultsPerPoll(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getWebhookUrl() const;
    bool webhookUrlIsSet() const;
    void unsetWebhook_url();

    void setWebhookUrl(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getWebhookSecret() const;
    bool webhookSecretIsSet() const;
    void unsetWebhook_secret();

    void setWebhookSecret(const utility::string_t& value);


protected:
    utility::string_t m_Tag;
    bool m_TagIsSet;
    utility::string_t m_Query;
    bool m_QueryIsSet;
    double m_Interval_seconds;
    bool m_Interval_secondsIsSet;
    int32_t m_Max_results_per_poll;
    bool m_Max_results_per_pollIsSet;
    utility::string_t m_Status;
    bool m_StatusIsSet;
    utility::string_t m_Webhook_url;
    bool m_Webhook_urlIsSet;
    utility::string_t m_Webhook_secret;
    bool m_Webhook_secretIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleUpdate_H_ */
