/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FilterRuleDeliveryLogListResponse.h
 *
 * Paginated filter rule delivery logs.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleDeliveryLogListResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleDeliveryLogListResponse_H_


#include "scrapebadger/ModelBase.h"

#include "scrapebadger/model/FilterRuleDeliveryLogResponse.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class FilterRuleDeliveryLogResponse;


/// <summary>
/// Paginated filter rule delivery logs.
/// </summary>
class  FilterRuleDeliveryLogListResponse
    : public ModelBase
{
public:
    FilterRuleDeliveryLogListResponse();
    virtual ~FilterRuleDeliveryLogListResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FilterRuleDeliveryLogListResponse members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<FilterRuleDeliveryLogResponse>>& getLogs();
    bool logsIsSet() const;
    void unsetLogs();

    void setLogs(const std::vector<std::shared_ptr<FilterRuleDeliveryLogResponse>>& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();

    void setTotal(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPage() const;
    bool pageIsSet() const;
    void unsetPage();

    void setPage(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPageSize() const;
    bool pageSizeIsSet() const;
    void unsetPage_size();

    void setPageSize(int32_t value);


protected:
    std::vector<std::shared_ptr<FilterRuleDeliveryLogResponse>> m_Logs;
    bool m_LogsIsSet;
    int32_t m_Total;
    bool m_TotalIsSet;
    int32_t m_Page;
    bool m_PageIsSet;
    int32_t m_Page_size;
    bool m_Page_sizeIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleDeliveryLogListResponse_H_ */
