/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FilterRuleResponse.h
 *
 * Filter rule response.  Per-poll billing — see &#x60;&#x60;GET /v1/twitter/filter-rules/pricing&#x60;&#x60; for the rates that apply globally to every rule.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleResponse_H_


#include "scrapebadger/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Filter rule response.  Per-poll billing — see &#x60;&#x60;GET /v1/twitter/filter-rules/pricing&#x60;&#x60; for the rates that apply globally to every rule.
/// </summary>
class  FilterRuleResponse
    : public ModelBase
{
public:
    FilterRuleResponse();
    virtual ~FilterRuleResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// FilterRuleResponse members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTag() const;
    bool tagIsSet() const;
    void unsetTag();

    void setTag(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getQuery() const;
    bool queryIsSet() const;
    void unsetQuery();

    void setQuery(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getIntervalSeconds() const;
    bool intervalSecondsIsSet() const;
    void unsetInterval_seconds();

    void setIntervalSeconds(double value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getMaxResultsPerPoll() const;
    bool maxResultsPerPollIsSet() const;
    void unsetMax_results_per_poll();

    void setMaxResultsPerPoll(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getStatusReason() const;
    bool statusReasonIsSet() const;
    void unsetStatus_reason();

    void setStatusReason(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getWebhookUrl() const;
    bool webhookUrlIsSet() const;
    void unsetWebhook_url();

    void setWebhookUrl(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    bool isWebhookSecretSet() const;
    bool webhookSecretSetIsSet() const;
    void unsetWebhook_secret_set();

    void setWebhookSecretSet(bool value);

    /// <summary>
    /// 
    /// </summary>
    double getTotalCreditsBurned() const;
    bool totalCreditsBurnedIsSet() const;
    void unsetTotal_credits_burned();

    void setTotalCreditsBurned(double value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getCreatedAt() const;
    bool createdAtIsSet() const;
    void unsetCreated_at();

    void setCreatedAt(const utility::datetime& value);

    /// <summary>
    /// 
    /// </summary>
    utility::datetime getUpdatedAt() const;
    bool updatedAtIsSet() const;
    void unsetUpdated_at();

    void setUpdatedAt(const utility::datetime& value);


protected:
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_Tag;
    bool m_TagIsSet;
    utility::string_t m_Query;
    bool m_QueryIsSet;
    double m_Interval_seconds;
    bool m_Interval_secondsIsSet;
    int32_t m_Max_results_per_poll;
    bool m_Max_results_per_pollIsSet;
    utility::string_t m_Status;
    bool m_StatusIsSet;
    utility::string_t m_Status_reason;
    bool m_Status_reasonIsSet;
    utility::string_t m_Webhook_url;
    bool m_Webhook_urlIsSet;
    bool m_Webhook_secret_set;
    bool m_Webhook_secret_setIsSet;
    double m_Total_credits_burned;
    bool m_Total_credits_burnedIsSet;
    utility::datetime m_Created_at;
    bool m_Created_atIsSet;
    utility::datetime m_Updated_at;
    bool m_Updated_atIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_FilterRuleResponse_H_ */
