/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MarketsResponse.h
 *
 * Envelope returned by the market reference endpoint.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_MarketsResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_MarketsResponse_H_


#include "scrapebadger/ModelBase.h"

#include "scrapebadger/AnyType.h"
#include <map>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Envelope returned by the market reference endpoint.
/// </summary>
class  MarketsResponse
    : public ModelBase
{
public:
    MarketsResponse();
    virtual ~MarketsResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// MarketsResponse members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>>& getMarkets();
    bool marketsIsSet() const;
    void unsetMarkets();

    void setMarkets(const std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>>& value);


protected:
    std::vector<std::map<utility::string_t, std::shared_ptr<AnyType>>> m_Markets;
    bool m_MarketsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_MarketsResponse_H_ */
