/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse.h
 *
 * Per-poll rates for filter rules (no tiers — usage-based).
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse_H_


#include "scrapebadger/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Per-poll rates for filter rules (no tiers — usage-based).
/// </summary>
class  Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse
    : public ModelBase
{
public:
    Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse();
    virtual ~Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse members

    /// <summary>
    /// 
    /// </summary>
    double getCreditsPerEmptyCall() const;
    bool creditsPerEmptyCallIsSet() const;
    void unsetCredits_per_empty_call();

    void setCreditsPerEmptyCall(double value);

    /// <summary>
    /// 
    /// </summary>
    double getCreditsPerTweetReturned() const;
    bool creditsPerTweetReturnedIsSet() const;
    void unsetCredits_per_tweet_returned();

    void setCreditsPerTweetReturned(double value);


protected:
    double m_Credits_per_empty_call;
    bool m_Credits_per_empty_callIsSet;
    double m_Credits_per_tweet_returned;
    bool m_Credits_per_tweet_returnedIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse_H_ */
