/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * UserProfileResponse.h
 *
 * Envelope returned by user profile.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_UserProfileResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_UserProfileResponse_H_


#include "scrapebadger/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "scrapebadger/model/VintedUserProfile.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class VintedUserProfile;


/// <summary>
/// Envelope returned by user profile.
/// </summary>
class  UserProfileResponse
    : public ModelBase
{
public:
    UserProfileResponse();
    virtual ~UserProfileResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// UserProfileResponse members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VintedUserProfile> getUser() const;
    bool userIsSet() const;
    void unsetUser();

    void setUser(const std::shared_ptr<VintedUserProfile>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMarket() const;
    bool marketIsSet() const;
    void unsetMarket();

    void setMarket(const utility::string_t& value);


protected:
    std::shared_ptr<VintedUserProfile> m_User;
    bool m_UserIsSet;
    utility::string_t m_Market;
    bool m_MarketIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_UserProfileResponse_H_ */
