/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * VintedItemDetail.h
 *
 * A single listing with the fields only the detail endpoint carries.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_VintedItemDetail_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_VintedItemDetail_H_


#include "scrapebadger/ModelBase.h"

#include "scrapebadger/model/VintedUserSummary.h"
#include "scrapebadger/model/VintedPhoto.h"
#include "scrapebadger/model/VintedPrice.h"
#include "scrapebadger/model/VintedSellerSummary.h"
#include <cpprest/details/basic_types.h>
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class VintedPrice;
class VintedUserSummary;
class VintedPhoto;
class VintedSellerSummary;


/// <summary>
/// A single listing with the fields only the detail endpoint carries.
/// </summary>
class  VintedItemDetail
    : public ModelBase
{
public:
    VintedItemDetail();
    virtual ~VintedItemDetail();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// VintedItemDetail members

    /// <summary>
    /// 
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTitle() const;
    bool titleIsSet() const;
    void unsetTitle();

    void setTitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VintedPrice> getPrice() const;
    bool priceIsSet() const;
    void unsetPrice();

    void setPrice(const std::shared_ptr<VintedPrice>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBrandTitle() const;
    bool brandTitleIsSet() const;
    void unsetBrand_title();

    void setBrandTitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDisplayTitle() const;
    bool displayTitleIsSet() const;
    void unsetDisplay_title();

    void setDisplayTitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDisplaySubtitle() const;
    bool displaySubtitleIsSet() const;
    void unsetDisplay_subtitle();

    void setDisplaySubtitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSizeTitle() const;
    bool sizeTitleIsSet() const;
    void unsetSize_title();

    void setSizeTitle(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getStatus() const;
    bool statusIsSet() const;
    void unsetStatus();

    void setStatus(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUrl() const;
    bool urlIsSet() const;
    void unsetUrl();

    void setUrl(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPath() const;
    bool pathIsSet() const;
    void unsetPath();

    void setPath(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    bool isIsVisible() const;
    bool isVisibleIsSet() const;
    void unsetIs_visible();

    void setIsVisible(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isPromoted() const;
    bool promotedIsSet() const;
    void unsetPromoted();

    void setPromoted(bool value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getFavouriteCount() const;
    bool favouriteCountIsSet() const;
    void unsetFavourite_count();

    void setFavouriteCount(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getViewCount() const;
    bool viewCountIsSet() const;
    void unsetView_count();

    void setViewCount(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getServiceFee() const;
    bool serviceFeeIsSet() const;
    void unsetService_fee();

    void setServiceFee(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getTotalItemPrice() const;
    bool totalItemPriceIsSet() const;
    void unsetTotal_item_price();

    void setTotalItemPrice(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getContentSource() const;
    bool contentSourceIsSet() const;
    void unsetContent_source();

    void setContentSource(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getSellerCountryCode() const;
    bool sellerCountryCodeIsSet() const;
    void unsetSeller_country_code();

    void setSellerCountryCode(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getSimilarityScore() const;
    bool similarityScoreIsSet() const;
    void unsetSimilarity_score();

    void setSimilarityScore(double value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VintedUserSummary> getUser() const;
    bool userIsSet() const;
    void unsetUser();

    void setUser(const std::shared_ptr<VintedUserSummary>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VintedPhoto> getPhoto() const;
    bool photoIsSet() const;
    void unsetPhoto();

    void setPhoto(const std::shared_ptr<VintedPhoto>& value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<VintedPhoto>>& getPhotos();
    bool photosIsSet() const;
    void unsetPhotos();

    void setPhotos(const std::vector<std::shared_ptr<VintedPhoto>>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDescription() const;
    bool descriptionIsSet() const;
    void unsetDescription();

    void setDescription(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getCatalogId() const;
    bool catalogIdIsSet() const;
    void unsetCatalog_id();

    void setCatalogId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getColor1() const;
    bool color1IsSet() const;
    void unsetColor1();

    void setColor1(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getColor2() const;
    bool color2IsSet() const;
    void unsetColor2();

    void setColor2(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPackageSizeId() const;
    bool packageSizeIdIsSet() const;
    void unsetPackage_size_id();

    void setPackageSizeId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    bool isIsFavourite() const;
    bool isFavouriteIsSet() const;
    void unsetIs_favourite();

    void setIsFavourite(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isCanBuy() const;
    bool canBuyIsSet() const;
    void unsetCan_buy();

    void setCanBuy(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isCanBundle() const;
    bool canBundleIsSet() const;
    void unsetCan_bundle();

    void setCanBundle(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isCanReserve() const;
    bool canReserveIsSet() const;
    void unsetCan_reserve();

    void setCanReserve(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isInstantBuy() const;
    bool instantBuyIsSet() const;
    void unsetInstant_buy();

    void setInstantBuy(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isIsHidden() const;
    bool isHiddenIsSet() const;
    void unsetIs_hidden();

    void setIsHidden(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isIsReserved() const;
    bool isReservedIsSet() const;
    void unsetIs_reserved();

    void setIsReserved(bool value);

    /// <summary>
    /// 
    /// </summary>
    bool isIsClosed() const;
    bool isClosedIsSet() const;
    void unsetIs_closed();

    void setIsClosed(bool value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<VintedSellerSummary> getSeller() const;
    bool sellerIsSet() const;
    void unsetSeller();

    void setSeller(const std::shared_ptr<VintedSellerSummary>& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getSizeId() const;
    bool sizeIdIsSet() const;
    void unsetSize_id();

    void setSizeId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getStatusId() const;
    bool statusIdIsSet() const;
    void unsetStatus_id();

    void setStatusId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getBrandId() const;
    bool brandIdIsSet() const;
    void unsetBrand_id();

    void setBrandId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getCategory();
    bool categoryIsSet() const;
    void unsetCategory();

    void setCategory(const std::vector<utility::string_t>& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUploadDate() const;
    bool uploadDateIsSet() const;
    void unsetUpload_date();

    void setUploadDate(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUploadedAt() const;
    bool uploadedAtIsSet() const;
    void unsetUploaded_at();

    void setUploadedAt(const utility::string_t& value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_Title;
    bool m_TitleIsSet;
    std::shared_ptr<VintedPrice> m_Price;
    bool m_PriceIsSet;
    utility::string_t m_Brand_title;
    bool m_Brand_titleIsSet;
    utility::string_t m_Display_title;
    bool m_Display_titleIsSet;
    utility::string_t m_Display_subtitle;
    bool m_Display_subtitleIsSet;
    utility::string_t m_Size_title;
    bool m_Size_titleIsSet;
    utility::string_t m_Status;
    bool m_StatusIsSet;
    utility::string_t m_Url;
    bool m_UrlIsSet;
    utility::string_t m_Path;
    bool m_PathIsSet;
    bool m_Is_visible;
    bool m_Is_visibleIsSet;
    bool m_Promoted;
    bool m_PromotedIsSet;
    int32_t m_Favourite_count;
    bool m_Favourite_countIsSet;
    int32_t m_View_count;
    bool m_View_countIsSet;
    utility::string_t m_Service_fee;
    bool m_Service_feeIsSet;
    utility::string_t m_Total_item_price;
    bool m_Total_item_priceIsSet;
    utility::string_t m_Content_source;
    bool m_Content_sourceIsSet;
    utility::string_t m_Seller_country_code;
    bool m_Seller_country_codeIsSet;
    double m_Similarity_score;
    bool m_Similarity_scoreIsSet;
    std::shared_ptr<VintedUserSummary> m_User;
    bool m_UserIsSet;
    std::shared_ptr<VintedPhoto> m_Photo;
    bool m_PhotoIsSet;
    std::vector<std::shared_ptr<VintedPhoto>> m_Photos;
    bool m_PhotosIsSet;
    utility::string_t m_Description;
    bool m_DescriptionIsSet;
    int32_t m_Catalog_id;
    bool m_Catalog_idIsSet;
    utility::string_t m_Color1;
    bool m_Color1IsSet;
    utility::string_t m_Color2;
    bool m_Color2IsSet;
    int32_t m_Package_size_id;
    bool m_Package_size_idIsSet;
    bool m_Is_favourite;
    bool m_Is_favouriteIsSet;
    bool m_Can_buy;
    bool m_Can_buyIsSet;
    bool m_Can_bundle;
    bool m_Can_bundleIsSet;
    bool m_Can_reserve;
    bool m_Can_reserveIsSet;
    bool m_Instant_buy;
    bool m_Instant_buyIsSet;
    bool m_Is_hidden;
    bool m_Is_hiddenIsSet;
    bool m_Is_reserved;
    bool m_Is_reservedIsSet;
    bool m_Is_closed;
    bool m_Is_closedIsSet;
    std::shared_ptr<VintedSellerSummary> m_Seller;
    bool m_SellerIsSet;
    int32_t m_Size_id;
    bool m_Size_idIsSet;
    int32_t m_Status_id;
    bool m_Status_idIsSet;
    int32_t m_Brand_id;
    bool m_Brand_idIsSet;
    std::vector<utility::string_t> m_Category;
    bool m_CategoryIsSet;
    utility::string_t m_Upload_date;
    bool m_Upload_dateIsSet;
    utility::string_t m_Uploaded_at;
    bool m_Uploaded_atIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_VintedItemDetail_H_ */
