/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * VintedMobileReadRequest.h
 *
 * Parameters are validated against the discoverable operation catalog.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_VintedMobileReadRequest_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_VintedMobileReadRequest_H_


#include "scrapebadger/ModelBase.h"

#include "scrapebadger/AnyType.h"
#include <cpprest/details/basic_types.h>
#include <map>

namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Parameters are validated against the discoverable operation catalog.
/// </summary>
class  VintedMobileReadRequest
    : public ModelBase
{
public:
    VintedMobileReadRequest();
    virtual ~VintedMobileReadRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// VintedMobileReadRequest members

    /// <summary>
    /// Vinted market code; uk aliases gb
    /// </summary>
    utility::string_t getMarket() const;
    bool marketIsSet() const;
    void unsetMarket();

    void setMarket(const utility::string_t& value);

    /// <summary>
    /// Operation-specific parameters. GET /v1/vinted/mobile/operations lists types, required fields and examples.
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<AnyType>>& getParameters();
    bool parametersIsSet() const;
    void unsetParameters();

    void setParameters(const std::map<utility::string_t, std::shared_ptr<AnyType>>& value);


protected:
    utility::string_t m_Market;
    bool m_MarketIsSet;
    std::map<utility::string_t, std::shared_ptr<AnyType>> m_Parameters;
    bool m_ParametersIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_VintedMobileReadRequest_H_ */
