/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * VintedPagination.h
 *
 * Page metadata. Resend &#x60;time&#x60; to page a search deterministically.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_VintedPagination_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_VintedPagination_H_


#include "scrapebadger/ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {



/// <summary>
/// Page metadata. Resend &#x60;time&#x60; to page a search deterministically.
/// </summary>
class  VintedPagination
    : public ModelBase
{
public:
    VintedPagination();
    virtual ~VintedPagination();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// VintedPagination members

    /// <summary>
    /// 
    /// </summary>
    int32_t getCurrentPage() const;
    bool currentPageIsSet() const;
    void unsetCurrent_page();

    void setCurrentPage(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotalPages() const;
    bool totalPagesIsSet() const;
    void unsetTotal_pages();

    void setTotalPages(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotalEntries() const;
    bool totalEntriesIsSet() const;
    void unsetTotal_entries();

    void setTotalEntries(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getPerPage() const;
    bool perPageIsSet() const;
    void unsetPer_page();

    void setPerPage(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTime() const;
    bool timeIsSet() const;
    void unsetTime();

    void setTime(int32_t value);


protected:
    int32_t m_Current_page;
    bool m_Current_pageIsSet;
    int32_t m_Total_pages;
    bool m_Total_pagesIsSet;
    int32_t m_Total_entries;
    bool m_Total_entriesIsSet;
    int32_t m_Per_page;
    bool m_Per_pageIsSet;
    int32_t m_Time;
    bool m_TimeIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_VintedPagination_H_ */
