/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WebhookListResponse.h
 *
 * List of webhooks.
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_WebhookListResponse_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_WebhookListResponse_H_


#include "scrapebadger/ModelBase.h"

#include "scrapebadger/model/WebhookListItem.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class WebhookListItem;


/// <summary>
/// List of webhooks.
/// </summary>
class  WebhookListResponse
    : public ModelBase
{
public:
    WebhookListResponse();
    virtual ~WebhookListResponse();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// WebhookListResponse members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<WebhookListItem>>& getWebhooks();
    bool webhooksIsSet() const;
    void unsetWebhooks();

    void setWebhooks(const std::vector<std::shared_ptr<WebhookListItem>>& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getTotal() const;
    bool totalIsSet() const;
    void unsetTotal();

    void setTotal(int32_t value);


protected:
    std::vector<std::shared_ptr<WebhookListItem>> m_Webhooks;
    bool m_WebhooksIsSet;
    int32_t m_Total;
    bool m_TotalIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_WebhookListResponse_H_ */
