/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AmazonApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_AmazonApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_AmazonApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  AmazonApi 
{
public:

    explicit AmazonApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~AmazonApi();

    /// <summary>
    /// Amazon scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Amazon scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> amazonAmazonScraperHealthCheck(
    ) const;
    /// <summary>
    /// Amazon scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Amazon scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> amazonAmazonScraperHealthCheckHead(
    ) const;
    /// <summary>
    /// Bestsellers by category
    /// </summary>
    /// <remarks>
    /// Top-selling products for a category (browse node).
    /// </remarks>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="category">Bestsellers node id or slug (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> amazonBestsellersByCategory(
        boost::optional<utility::string_t> domain,
        boost::optional<utility::string_t> category,
        boost::optional<int32_t> page
    ) const;
    /// <summary>
    /// Browse-node category listing
    /// </summary>
    /// <remarks>
    /// List products within an Amazon browse-node category.
    /// </remarks>
    /// <param name="node">Amazon browse-node id</param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="sortBy"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> amazonBrowseNodeCategoryListing(
        utility::string_t node,
        boost::optional<utility::string_t> domain,
        boost::optional<int32_t> page,
        boost::optional<utility::string_t> sortBy
    ) const;
    /// <summary>
    /// Get all seller offers (buybox)
    /// </summary>
    /// <remarks>
    /// All third-party offers for an ASIN, including the Buy Box winner.
    /// </remarks>
    /// <param name="asin"></param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="zip"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> amazonGetAllSellerOffersBuybox(
        utility::string_t asin,
        boost::optional<utility::string_t> domain,
        boost::optional<utility::string_t> zip
    ) const;
    /// <summary>
    /// Get product detail
    /// </summary>
    /// <remarks>
    /// Full product detail by ASIN (price, variants, badges, buybox, ranks…).
    /// </remarks>
    /// <param name="asin"></param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="zip">Delivery postal/zip for localized buybox (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="language"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> amazonGetProductDetail(
        utility::string_t asin,
        boost::optional<utility::string_t> domain,
        boost::optional<utility::string_t> zip,
        boost::optional<utility::string_t> language
    ) const;
    /// <summary>
    /// Get product reviews
    /// </summary>
    /// <remarks>
    /// Customer reviews for an ASIN (featured + paginated, with filters).
    /// </remarks>
    /// <param name="asin"></param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page">Review page (1-100, ~10 reviews/page) (optional, default to 0)</param>
    /// <param name="sortBy">helpful | recent (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="star">one_star..five_star | positive | critical (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="verifiedOnly"> (optional, default to false)</param>
    /// <param name="mediaOnly"> (optional, default to false)</param>
    pplx::task<std::shared_ptr<AnyType>> amazonGetProductReviews(
        utility::string_t asin,
        boost::optional<utility::string_t> domain,
        boost::optional<int32_t> page,
        boost::optional<utility::string_t> sortBy,
        boost::optional<utility::string_t> star,
        boost::optional<bool> verifiedOnly,
        boost::optional<bool> mediaOnly
    ) const;
    /// <summary>
    /// Get seller feedback
    /// </summary>
    /// <remarks>
    /// Buyer feedback entries for a seller.
    /// </remarks>
    /// <param name="sellerId"></param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> amazonGetSellerFeedback(
        utility::string_t sellerId,
        boost::optional<utility::string_t> domain,
        boost::optional<int32_t> page
    ) const;
    /// <summary>
    /// Get seller profile
    /// </summary>
    /// <remarks>
    /// Seller profile, ratings and feedback summary.
    /// </remarks>
    /// <param name="sellerId"></param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> amazonGetSellerProfile(
        utility::string_t sellerId,
        boost::optional<utility::string_t> domain
    ) const;
    /// <summary>
    /// Get seller storefront products
    /// </summary>
    /// <remarks>
    /// Products listed in a seller&#39;s storefront.
    /// </remarks>
    /// <param name="sellerId"></param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> amazonGetSellerStorefrontProducts(
        utility::string_t sellerId,
        boost::optional<utility::string_t> domain,
        boost::optional<int32_t> page
    ) const;
    /// <summary>
    /// Keyword suggestions
    /// </summary>
    /// <remarks>
    /// Get Amazon search autocomplete suggestions for keyword research.
    /// </remarks>
    /// <param name="query">Partial search term</param>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> amazonKeywordSuggestions(
        utility::string_t query,
        boost::optional<utility::string_t> domain
    ) const;
    /// <summary>
    /// List category aliases
    /// </summary>
    /// <remarks>
    /// List common Amazon department/category aliases and bestseller nodes.
    /// </remarks>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> amazonListCategoryAliases(
        boost::optional<utility::string_t> domain
    ) const;
    /// <summary>
    /// List marketplaces
    /// </summary>
    /// <remarks>
    /// List all supported Amazon marketplaces.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> amazonListMarketplaces(
    ) const;
    /// <summary>
    /// New releases by category
    /// </summary>
    /// <remarks>
    /// Newly released products for a category (browse node).
    /// </remarks>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="category"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> amazonNewReleasesByCategory(
        boost::optional<utility::string_t> domain,
        boost::optional<utility::string_t> category,
        boost::optional<int32_t> page
    ) const;
    /// <summary>
    /// Search Amazon products
    /// </summary>
    /// <remarks>
    /// Search the Amazon catalog with filters and sorting.
    /// </remarks>
    /// <param name="query">Search keywords</param>
    /// <param name="domain">Amazon marketplace TLD or code (com, co.uk, de…) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="sortBy">relevance | price_low_to_high | price_high_to_low | avg_review | newest (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="category">Department/category alias (i&#x3D; param) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="minPrice"> (optional, default to 0.0)</param>
    /// <param name="maxPrice"> (optional, default to 0.0)</param>
    /// <param name="zip">Delivery postal/zip code for localized pricing (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="language">Locale for results, e.g. en_US, fr_FR (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> amazonSearchAmazonProducts(
        utility::string_t query,
        boost::optional<utility::string_t> domain,
        boost::optional<int32_t> page,
        boost::optional<utility::string_t> sortBy,
        boost::optional<utility::string_t> category,
        boost::optional<double> minPrice,
        boost::optional<double> maxPrice,
        boost::optional<utility::string_t> zip,
        boost::optional<utility::string_t> language
    ) const;
    /// <summary>
    /// Today&#39;s deals
    /// </summary>
    /// <remarks>
    /// Current Amazon deals (lightning deals, best deals).
    /// </remarks>
    /// <param name="domain"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="category"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> amazonTodaySDeals(
        boost::optional<utility::string_t> domain,
        boost::optional<utility::string_t> category,
        boost::optional<int32_t> page
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_AmazonApi_H_ */

