/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * LinkedInApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_LinkedInApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_LinkedInApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  LinkedInApi 
{
public:

    explicit LinkedInApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~LinkedInApi();

    /// <summary>
    /// Get a company&#39;s job postings
    /// </summary>
    /// <remarks>
    /// Public job postings for a company (numeric company id from the company endpoint).
    /// </remarks>
    /// <param name="companyId"></param>
    /// <param name="start">Pagination offset (0, 25, 50, ...) (optional, default to 0)</param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetACompanySJobPostings(
        utility::string_t companyId,
        boost::optional<int32_t> start,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Get a course
    /// </summary>
    /// <remarks>
    /// A public LinkedIn Learning course — provider, workload, instructors, rating.
    /// </remarks>
    /// <param name="courseSlug"></param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetACourse(
        utility::string_t courseSlug,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Get a public article
    /// </summary>
    /// <remarks>
    /// A public Pulse article — title, body, author, reactions (JSON-LD).
    /// </remarks>
    /// <param name="articleSlug"></param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetAPublicArticle(
        utility::string_t articleSlug,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Get a public post
    /// </summary>
    /// <remarks>
    /// A public activity share — text, author, reactions, comments (JSON-LD).
    /// </remarks>
    /// <param name="postSlug"></param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetAPublicPost(
        utility::string_t postSlug,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Get company
    /// </summary>
    /// <remarks>
    /// Public company page — industry, size, HQ, followers, specialties (JSON-LD + SSR).
    /// </remarks>
    /// <param name="universalName"></param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetCompany(
        utility::string_t universalName,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Get job detail
    /// </summary>
    /// <remarks>
    /// Full detail for one job posting (guest API, no login).
    /// </remarks>
    /// <param name="jobId"></param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetJobDetail(
        utility::string_t jobId,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Get public profile
    /// </summary>
    /// <remarks>
    /// Public profile by vanity id (the &#x60;&#x60;/in/{public_id}&#x60;&#x60; slug) — name, headline, location, about, experience, education (public JSON-LD + SSR subset).
    /// </remarks>
    /// <param name="publicId"></param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetPublicProfile(
        utility::string_t publicId,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Get school
    /// </summary>
    /// <remarks>
    /// Public school page — name, description, website, follower/alumni counts.
    /// </remarks>
    /// <param name="universalName"></param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinGetSchool(
        utility::string_t universalName,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// LinkedIn scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the LinkedIn scraper service (accepts HEAD).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> linkedinLinkedinScraperHealthCheck(
    ) const;
    /// <summary>
    /// LinkedIn scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the LinkedIn scraper service (accepts HEAD).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> linkedinLinkedinScraperHealthCheckHead(
    ) const;
    /// <summary>
    /// Search LinkedIn jobs
    /// </summary>
    /// <remarks>
    /// Search public LinkedIn job postings (guest API, no login).
    /// </remarks>
    /// <param name="keywords">Job title / keywords (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="location">Location text, e.g. &#39;New York&#39; (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="geoId">LinkedIn numeric geo id (overrides location) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="companyId">Restrict to a company (numeric id) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="datePosted">past_24h | past_week | past_month | any (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="experience">internship|entry|associate|mid_senior|director|executive (comma-separated) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="jobType">full_time|part_time|contract|temporary|internship|volunteer|other (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="workplace">onsite|remote|hybrid (comma-separated) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sort">relevant | recent (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="start">Pagination offset (0, 25, 50, ...) (optional, default to 0)</param>
    /// <param name="country">Residential proxy country (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinSearchLinkedinJobs(
        boost::optional<utility::string_t> keywords,
        boost::optional<utility::string_t> location,
        boost::optional<utility::string_t> geoId,
        boost::optional<utility::string_t> companyId,
        boost::optional<utility::string_t> datePosted,
        boost::optional<utility::string_t> experience,
        boost::optional<utility::string_t> jobType,
        boost::optional<utility::string_t> workplace,
        boost::optional<utility::string_t> sort,
        boost::optional<int32_t> start,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Suggest location geo ids
    /// </summary>
    /// <remarks>
    /// Resolve a name to LinkedIn ids (job-search &#x60;&#x60;geo_id&#x60;&#x60; / &#x60;&#x60;company_id&#x60;&#x60; helper).
    /// </remarks>
    /// <param name="query">Location text, e.g. &#39;London&#39;</param>
    /// <param name="type">geo | company (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> linkedinSuggestLocationGeoIds(
        utility::string_t query,
        boost::optional<utility::string_t> type
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_LinkedInApi_H_ */

