/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PerplexityApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_PerplexityApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_PerplexityApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  PerplexityApi 
{
public:

    explicit PerplexityApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~PerplexityApi();

    /// <summary>
    /// Ask Perplexity a question
    /// </summary>
    /// <remarks>
    /// Send a prompt to Perplexity and get the answer plus the web sources it cited.
    /// </remarks>
    /// <param name="prompt">The prompt to send to Perplexity (max 4096 characters).</param>
    /// <param name="country">ISO-3166 alpha-2 egress country, e.g. &#39;US&#39;, &#39;GB&#39;, &#39;DE&#39;. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> perplexityAskPerplexityAQuestion(
        utility::string_t prompt,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Ask Perplexity a question (POST)
    /// </summary>
    /// <remarks>
    /// POST form of &#x60;/ask&#x60;, for prompts too long for a query string.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> perplexityAskPerplexityAQuestionPost(
    ) const;
    /// <summary>
    /// Measure a brand&#39;s visibility in a Perplexity answer
    /// </summary>
    /// <remarks>
    /// Ask Perplexity, then report whether the brand is mentioned, cited and how prominently.
    /// </remarks>
    /// <param name="prompt">The prompt to ask Perplexity.</param>
    /// <param name="brand">Brand name to look for in the answer.</param>
    /// <param name="domain">Brand domain, for citation matching. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="aliases">Comma-separated alternative names. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="competitors">Comma-separated competitor names. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="country">ISO-3166 alpha-2 egress country. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> perplexityMeasureABrandSVisibilityInAPerplexityAnswer(
        utility::string_t prompt,
        utility::string_t brand,
        boost::optional<utility::string_t> domain,
        boost::optional<utility::string_t> aliases,
        boost::optional<utility::string_t> competitors,
        boost::optional<utility::string_t> country
    ) const;
    /// <summary>
    /// Measure a brand&#39;s visibility in a Perplexity answer (POST)
    /// </summary>
    /// <remarks>
    /// POST form, for longer prompts and larger competitor sets.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> perplexityMeasureABrandSVisibilityInAPerplexityAnswerPost(
    ) const;
    /// <summary>
    /// Perplexity scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Perplexity scraper service (accepts HEAD).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> perplexityPerplexityScraperHealthCheck(
    ) const;
    /// <summary>
    /// Perplexity scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Perplexity scraper service (accepts HEAD).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> perplexityPerplexityScraperHealthCheckHead(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_PerplexityApi_H_ */

