/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RedfinApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_RedfinApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_RedfinApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  RedfinApi 
{
public:

    explicit RedfinApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~RedfinApi();

    /// <summary>
    /// Get agent profile + listings
    /// </summary>
    /// <remarks>
    /// Get a Redfin real-estate agent&#39;s profile and their active listings.
    /// </remarks>
    /// <param name="url">Full Redfin /realestateagents/ URL (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="agentId">Redfin agent id (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> redfinGetAgentProfileListings(
        boost::optional<utility::string_t> url,
        boost::optional<utility::string_t> agentId
    ) const;
    /// <summary>
    /// Get property detail
    /// </summary>
    /// <remarks>
    /// Get a single Redfin property&#39;s full detail by its numeric propertyId.
    /// </remarks>
    /// <param name="propertyId"></param>
    pplx::task<std::shared_ptr<AnyType>> redfinGetPropertyDetail(
        utility::string_t propertyId
    ) const;
    /// <summary>
    /// Get property detail by URL
    /// </summary>
    /// <remarks>
    /// Get a single Redfin property&#39;s full detail by its home URL.
    /// </remarks>
    /// <param name="url">Full Redfin property URL (/CA/City/.../home/12345678)</param>
    pplx::task<std::shared_ptr<AnyType>> redfinGetPropertyDetailByUrl(
        utility::string_t url
    ) const;
    /// <summary>
    /// List coverage markets
    /// </summary>
    /// <remarks>
    /// List Redfin coverage regions (US).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> redfinListCoverageMarkets(
    ) const;
    /// <summary>
    /// Redfin scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Redfin scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> redfinRedfinScraperHealthCheck(
    ) const;
    /// <summary>
    /// Redfin scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Redfin scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> redfinRedfinScraperHealthCheckHead(
    ) const;
    /// <summary>
    /// Region/address suggestions
    /// </summary>
    /// <remarks>
    /// Resolve a search term to Redfin regions/addresses.
    /// </remarks>
    /// <param name="query">Partial location — city, ZIP, address, neighborhood</param>
    pplx::task<std::shared_ptr<AnyType>> redfinRegionAddressSuggestions(
        utility::string_t query
    ) const;
    /// <summary>
    /// Search properties
    /// </summary>
    /// <remarks>
    /// Search Redfin for for-sale / for-rent / recently-sold properties.
    /// </remarks>
    /// <param name="location">City/state, ZIP, address or neighborhood</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="sort">relevant|newest|price_high_to_low|price_low_to_high|square_feet|lot_size|price_per_sqft|beds|baths (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="priceMin"> (optional, default to 0)</param>
    /// <param name="priceMax"> (optional, default to 0)</param>
    /// <param name="bedsMin"> (optional, default to 0)</param>
    /// <param name="bathsMin"> (optional, default to 0.0)</param>
    /// <param name="homeType">house|condo|townhouse|multi_family|land|mobile|coop|other (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sqftMin"> (optional, default to 0)</param>
    /// <param name="sqftMax"> (optional, default to 0)</param>
    /// <param name="lotMin"> (optional, default to 0)</param>
    /// <param name="lotMax"> (optional, default to 0)</param>
    /// <param name="yearBuiltMin"> (optional, default to 0)</param>
    /// <param name="yearBuiltMax"> (optional, default to 0)</param>
    /// <param name="maxDaysOnMarket"> (optional, default to 0)</param>
    /// <param name="north">Map bounds for tiling past the cap (optional, default to 0.0)</param>
    /// <param name="south"> (optional, default to 0.0)</param>
    /// <param name="east"> (optional, default to 0.0)</param>
    /// <param name="west"> (optional, default to 0.0)</param>
    pplx::task<std::shared_ptr<AnyType>> redfinSearchProperties(
        utility::string_t location,
        boost::optional<int32_t> page,
        boost::optional<utility::string_t> sort,
        boost::optional<int32_t> priceMin,
        boost::optional<int32_t> priceMax,
        boost::optional<int32_t> bedsMin,
        boost::optional<double> bathsMin,
        boost::optional<utility::string_t> homeType,
        boost::optional<int32_t> sqftMin,
        boost::optional<int32_t> sqftMax,
        boost::optional<int32_t> lotMin,
        boost::optional<int32_t> lotMax,
        boost::optional<int32_t> yearBuiltMin,
        boost::optional<int32_t> yearBuiltMax,
        boost::optional<int32_t> maxDaysOnMarket,
        boost::optional<double> north,
        boost::optional<double> south,
        boost::optional<double> east,
        boost::optional<double> west
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_RedfinApi_H_ */

