/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * TwitterApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_TwitterApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_TwitterApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/BillingLogListResponse.h"
#include "scrapebadger/model/FilterRuleCreate.h"
#include "scrapebadger/model/FilterRuleDeliveryLogListResponse.h"
#include "scrapebadger/model/FilterRuleListResponse.h"
#include "scrapebadger/model/FilterRuleResponse.h"
#include "scrapebadger/model/FilterRuleUpdate.h"
#include "scrapebadger/model/FilterRuleValidateRequest.h"
#include "scrapebadger/model/FilterRuleValidateResponse.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include "scrapebadger/model/Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse.h"
#include "scrapebadger/model/StreamMonitorCreate.h"
#include "scrapebadger/model/StreamMonitorListResponse.h"
#include "scrapebadger/model/StreamMonitorResponse.h"
#include "scrapebadger/model/StreamMonitorUpdate.h"
#include "scrapebadger/model/TweetDeliveryLogListResponse.h"
#include "scrapebadger/model/WebhookCreate.h"
#include "scrapebadger/model/WebhookListResponse.h"
#include "scrapebadger/model/WebhookResponse.h"
#include "scrapebadger/model/WebhookTestRequest.h"
#include "scrapebadger/model/WebhookTestResponse.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  TwitterApi 
{
public:

    explicit TwitterApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~TwitterApi();

    /// <summary>
    /// Advanced tweet search
    /// </summary>
    /// <remarks>
    /// Search tweets with advanced options.
    /// </remarks>
    /// <param name="query"></param>
    /// <param name="queryType"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="count"> (optional, default to 0)</param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterAdvancedTweetSearch(
        utility::string_t query,
        boost::optional<utility::string_t> queryType,
        boost::optional<int32_t> count,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Batch get users by IDs
    /// </summary>
    /// <remarks>
    /// Get multiple user profiles by their numeric IDs (comma-separated).
    /// </remarks>
    /// <param name="userIds"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterBatchGetUsersByIds(
        utility::string_t userIds
    ) const;
    /// <summary>
    /// Batch get users by usernames
    /// </summary>
    /// <remarks>
    /// Get multiple user profiles by their usernames (comma-separated).
    /// </remarks>
    /// <param name="usernames"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterBatchGetUsersByUsernames(
        utility::string_t usernames
    ) const;
    /// <summary>
    /// Configure webhook on a monitor
    /// </summary>
    /// <remarks>
    /// Configure a webhook delivery URL on a stream monitor.  The secret is returned only once on creation. Subsequent calls show secret_set: bool. If monitor already has a webhook, delete it first (409 is returned).
    /// </remarks>
    /// <param name="webhookCreate"></param>
    pplx::task<std::shared_ptr<WebhookResponse>> twitterConfigureWebhookOnAMonitor(
        std::shared_ptr<WebhookCreate> webhookCreate
    ) const;
    /// <summary>
    /// Create filter rule
    /// </summary>
    /// <remarks>
    /// Create a new query-based tweet filter rule.  The rule starts in &#39;active&#39; status immediately. Credits must be positive. The (api_key_id, tag) pair must be unique.
    /// </remarks>
    /// <param name="filterRuleCreate"></param>
    pplx::task<std::shared_ptr<FilterRuleResponse>> twitterCreateFilterRule(
        std::shared_ptr<FilterRuleCreate> filterRuleCreate
    ) const;
    /// <summary>
    /// Create stream monitor
    /// </summary>
    /// <remarks>
    /// Create a new stream monitor to watch Twitter accounts in real-time.
    /// </remarks>
    /// <param name="streamMonitorCreate"></param>
    pplx::task<std::shared_ptr<StreamMonitorResponse>> twitterCreateStreamMonitor(
        std::shared_ptr<StreamMonitorCreate> streamMonitorCreate
    ) const;
    /// <summary>
    /// Delete filter rule
    /// </summary>
    /// <remarks>
    /// Delete a filter rule and all its logs.
    /// </remarks>
    /// <param name="ruleId"></param>
    pplx::task<void> twitterDeleteFilterRule(
        utility::string_t ruleId
    ) const;
    /// <summary>
    /// Delete stream monitor
    /// </summary>
    /// <remarks>
    /// Delete a stream monitor and all its logs.
    /// </remarks>
    /// <param name="monitorId"></param>
    pplx::task<void> twitterDeleteStreamMonitor(
        utility::string_t monitorId
    ) const;
    /// <summary>
    /// Get article by ID
    /// </summary>
    /// <remarks>
    /// Get a long-form article by its ID.
    /// </remarks>
    /// <param name="articleId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetArticleById(
        utility::string_t articleId
    ) const;
    /// <summary>
    /// Get broadcast details
    /// </summary>
    /// <remarks>
    /// Get details of a live video broadcast.
    /// </remarks>
    /// <param name="broadcastId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetBroadcastDetails(
        utility::string_t broadcastId
    ) const;
    /// <summary>
    /// Get community details
    /// </summary>
    /// <remarks>
    /// Get details of a specific community.
    /// </remarks>
    /// <param name="communityId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetCommunityDetails(
        utility::string_t communityId
    ) const;
    /// <summary>
    /// Get community notes
    /// </summary>
    /// <remarks>
    /// Get community notes (Birdwatch) for a specific tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetCommunityNotes(
        utility::string_t tweetId
    ) const;
    /// <summary>
    /// Get community tweets
    /// </summary>
    /// <remarks>
    /// Get tweets from a specific community.
    /// </remarks>
    /// <param name="communityId"></param>
    /// <param name="tweetType"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetCommunityTweets(
        utility::string_t communityId,
        boost::optional<utility::string_t> tweetType,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get filter rule
    /// </summary>
    /// <remarks>
    /// Get a single filter rule by ID.
    /// </remarks>
    /// <param name="ruleId"></param>
    pplx::task<std::shared_ptr<FilterRuleResponse>> twitterGetFilterRule(
        utility::string_t ruleId
    ) const;
    /// <summary>
    /// Get filter rule per-poll rates
    /// </summary>
    /// <remarks>
    /// Current per-poll rates (auth required — used by SDK + dashboard).
    /// </remarks>
    pplx::task<std::shared_ptr<Portal_api__routers__v1_twitter_filter_rules__FilterRulePricingResponse>> twitterGetFilterRulePerPollRates(
    ) const;
    /// <summary>
    /// Get list details
    /// </summary>
    /// <remarks>
    /// Get details of a specific list.
    /// </remarks>
    /// <param name="listId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetListDetails(
        utility::string_t listId
    ) const;
    /// <summary>
    /// Get list tweets
    /// </summary>
    /// <remarks>
    /// Get tweets from a specific list.
    /// </remarks>
    /// <param name="listId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetListTweets(
        utility::string_t listId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get place details
    /// </summary>
    /// <remarks>
    /// Get details of a specific place.
    /// </remarks>
    /// <param name="placeId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetPlaceDetails(
        utility::string_t placeId
    ) const;
    /// <summary>
    /// Get similar tweets
    /// </summary>
    /// <remarks>
    /// Get tweets similar to a specific tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetSimilarTweets(
        utility::string_t tweetId
    ) const;
    /// <summary>
    /// Get Space details
    /// </summary>
    /// <remarks>
    /// Get details of a Twitter Space.
    /// </remarks>
    /// <param name="spaceId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetSpaceDetails(
        utility::string_t spaceId
    ) const;
    /// <summary>
    /// Get stream monitor
    /// </summary>
    /// <remarks>
    /// Get a single stream monitor by ID.
    /// </remarks>
    /// <param name="monitorId"></param>
    pplx::task<std::shared_ptr<StreamMonitorResponse>> twitterGetStreamMonitor(
        utility::string_t monitorId
    ) const;
    /// <summary>
    /// Get trending topics
    /// </summary>
    /// <remarks>
    /// Get trending topics.
    /// </remarks>
    /// <param name="category"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="count"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTrendingTopics(
        boost::optional<utility::string_t> category,
        boost::optional<int32_t> count
    ) const;
    /// <summary>
    /// Get trends by location
    /// </summary>
    /// <remarks>
    /// Get trending topics for a specific location (WOEID).
    /// </remarks>
    /// <param name="woeid"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTrendsByLocation(
        utility::string_t woeid
    ) const;
    /// <summary>
    /// Get tweet details
    /// </summary>
    /// <remarks>
    /// Get detailed information about a specific tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTweetDetails(
        utility::string_t tweetId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get tweet edit history
    /// </summary>
    /// <remarks>
    /// Get the edit history of a tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTweetEditHistory(
        utility::string_t tweetId
    ) const;
    /// <summary>
    /// Get tweet favoriters
    /// </summary>
    /// <remarks>
    /// Get users who favorited a specific tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTweetFavoriters(
        utility::string_t tweetId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get tweet quotes
    /// </summary>
    /// <remarks>
    /// Get tweets that quote a specific tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTweetQuotes(
        utility::string_t tweetId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get tweet replies
    /// </summary>
    /// <remarks>
    /// Get replies to a specific tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTweetReplies(
        utility::string_t tweetId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get tweet retweeters
    /// </summary>
    /// <remarks>
    /// Get users who retweeted a specific tweet.
    /// </remarks>
    /// <param name="tweetId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTweetRetweeters(
        utility::string_t tweetId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get tweets by IDs
    /// </summary>
    /// <remarks>
    /// Get multiple tweets by their IDs.
    /// </remarks>
    /// <param name="tweets"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetTweetsByIds(
        utility::string_t tweets
    ) const;
    /// <summary>
    /// Get user articles
    /// </summary>
    /// <remarks>
    /// Get long-form articles written by a user.
    /// </remarks>
    /// <param name="userId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserArticles(
        utility::string_t userId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get user by ID
    /// </summary>
    /// <remarks>
    /// Get user profile by user ID.
    /// </remarks>
    /// <param name="userId"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserById(
        utility::string_t userId
    ) const;
    /// <summary>
    /// Get user by username
    /// </summary>
    /// <remarks>
    /// Get user profile by username.
    /// </remarks>
    /// <param name="username"></param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserByUsername(
        utility::string_t username
    ) const;
    /// <summary>
    /// Get user followers
    /// </summary>
    /// <remarks>
    /// Get followers of a specific user.
    /// </remarks>
    /// <param name="username"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserFollowers(
        utility::string_t username,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get user following
    /// </summary>
    /// <remarks>
    /// Get users that a specific user is following.
    /// </remarks>
    /// <param name="username"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserFollowing(
        utility::string_t username,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get user mentions
    /// </summary>
    /// <remarks>
    /// Get tweets mentioning a specific user.
    /// </remarks>
    /// <param name="username"></param>
    /// <param name="count"> (optional, default to 0)</param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserMentions(
        utility::string_t username,
        boost::optional<int32_t> count,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get user subscriptions
    /// </summary>
    /// <remarks>
    /// Get subscriptions of a specific user.
    /// </remarks>
    /// <param name="userId"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserSubscriptions(
        utility::string_t userId,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Get user tweets
    /// </summary>
    /// <remarks>
    /// Get latest tweets from a specific user.
    /// </remarks>
    /// <param name="username"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterGetUserTweets(
        utility::string_t username,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// List billing logs
    /// </summary>
    /// <remarks>
    /// List billing activity logs for the authenticated API key&#39;s monitors.
    /// </remarks>
    /// <param name="monitorId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<BillingLogListResponse>> twitterListBillingLogs(
        boost::optional<utility::string_t> monitorId,
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize
    ) const;
    /// <summary>
    /// List delivery logs for a filter rule
    /// </summary>
    /// <remarks>
    /// List tweet delivery logs for a specific filter rule.
    /// </remarks>
    /// <param name="ruleId"></param>
    /// <param name="deliveryStatus"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="authorUsername"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    /// <param name="sort"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<FilterRuleDeliveryLogListResponse>> twitterListDeliveryLogsForAFilterRule(
        utility::string_t ruleId,
        boost::optional<utility::string_t> deliveryStatus,
        boost::optional<utility::string_t> authorUsername,
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize,
        boost::optional<utility::string_t> sort
    ) const;
    /// <summary>
    /// List filter rules
    /// </summary>
    /// <remarks>
    /// List all filter rules for the authenticated API key.
    /// </remarks>
    /// <param name="status"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<FilterRuleListResponse>> twitterListFilterRules(
        boost::optional<utility::string_t> status,
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize
    ) const;
    /// <summary>
    /// List stream monitors
    /// </summary>
    /// <remarks>
    /// List all stream monitors for the authenticated API key.
    /// </remarks>
    /// <param name="status"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<StreamMonitorListResponse>> twitterListStreamMonitors(
        boost::optional<utility::string_t> status,
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize
    ) const;
    /// <summary>
    /// List tweet delivery logs
    /// </summary>
    /// <remarks>
    /// List tweet delivery logs for the authenticated API key&#39;s monitors.
    /// </remarks>
    /// <param name="monitorId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="authorUsername"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="deliveryStatus"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="pageSize"> (optional, default to 0)</param>
    /// <param name="sort"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<TweetDeliveryLogListResponse>> twitterListTweetDeliveryLogs(
        boost::optional<utility::string_t> monitorId,
        boost::optional<utility::string_t> authorUsername,
        boost::optional<utility::string_t> deliveryStatus,
        boost::optional<int32_t> page,
        boost::optional<int32_t> pageSize,
        boost::optional<utility::string_t> sort
    ) const;
    /// <summary>
    /// List webhooks
    /// </summary>
    /// <remarks>
    /// List all webhook-configured monitors for the authenticated API key.
    /// </remarks>
    /// <param name="monitorId"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<WebhookListResponse>> twitterListWebhooks(
        boost::optional<utility::string_t> monitorId
    ) const;
    /// <summary>
    /// Remove webhook from monitor
    /// </summary>
    /// <remarks>
    /// Remove webhook configuration from a monitor. webhook_id is the monitor_id.
    /// </remarks>
    /// <param name="webhookId"></param>
    pplx::task<void> twitterRemoveWebhookFromMonitor(
        utility::string_t webhookId
    ) const;
    /// <summary>
    /// Search communities
    /// </summary>
    /// <remarks>
    /// Search for communities by query.
    /// </remarks>
    /// <param name="query"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterSearchCommunities(
        utility::string_t query,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Search list tweets
    /// </summary>
    /// <remarks>
    /// Search tweets within a specific list.
    /// </remarks>
    /// <param name="listId"></param>
    /// <param name="query"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterSearchListTweets(
        utility::string_t listId,
        utility::string_t query,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Search places
    /// </summary>
    /// <remarks>
    /// Search for places by query or coordinates.
    /// </remarks>
    /// <param name="query"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="lat"> (optional, default to 0.0)</param>
    /// <param name="r_long"> (optional, default to 0.0)</param>
    pplx::task<std::shared_ptr<AnyType>> twitterSearchPlaces(
        boost::optional<utility::string_t> query,
        boost::optional<double> lat,
        boost::optional<double> r_long
    ) const;
    /// <summary>
    /// Search users
    /// </summary>
    /// <remarks>
    /// Search for users by query.
    /// </remarks>
    /// <param name="query"></param>
    /// <param name="cursor"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> twitterSearchUsers(
        utility::string_t query,
        boost::optional<utility::string_t> cursor
    ) const;
    /// <summary>
    /// Test webhook delivery
    /// </summary>
    /// <remarks>
    /// Send a test payload to a monitor&#39;s webhook URL.  The test payload has type&#x3D;\&quot;test\&quot; instead of type&#x3D;\&quot;tweet\&quot;. Makes a synchronous HTTP POST and returns the delivery result.
    /// </remarks>
    /// <param name="webhookTestRequest"></param>
    pplx::task<std::shared_ptr<WebhookTestResponse>> twitterTestWebhookDelivery(
        std::shared_ptr<WebhookTestRequest> webhookTestRequest
    ) const;
    /// <summary>
    /// Twitter scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Twitter scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> twitterTwitterScraperHealthCheck(
    ) const;
    /// <summary>
    /// Twitter scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Twitter scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> twitterTwitterScraperHealthCheckHead(
    ) const;
    /// <summary>
    /// Update filter rule
    /// </summary>
    /// <remarks>
    /// Partially update a filter rule.  Setting status&#x3D;&#39;active&#39; on a paused rule performs a credit check.
    /// </remarks>
    /// <param name="ruleId"></param>
    /// <param name="filterRuleUpdate"></param>
    pplx::task<std::shared_ptr<FilterRuleResponse>> twitterUpdateFilterRule(
        utility::string_t ruleId,
        std::shared_ptr<FilterRuleUpdate> filterRuleUpdate
    ) const;
    /// <summary>
    /// Update stream monitor
    /// </summary>
    /// <remarks>
    /// Partially update a stream monitor.
    /// </remarks>
    /// <param name="monitorId"></param>
    /// <param name="streamMonitorUpdate"></param>
    pplx::task<std::shared_ptr<StreamMonitorResponse>> twitterUpdateStreamMonitor(
        utility::string_t monitorId,
        std::shared_ptr<StreamMonitorUpdate> streamMonitorUpdate
    ) const;
    /// <summary>
    /// Validate search query
    /// </summary>
    /// <remarks>
    /// Validate a Twitter search query string.  Performs basic structural validation without making a live Twitter request. Returns valid&#x3D;True if the query passes syntax checks.
    /// </remarks>
    /// <param name="filterRuleValidateRequest"></param>
    pplx::task<std::shared_ptr<FilterRuleValidateResponse>> twitterValidateSearchQuery(
        std::shared_ptr<FilterRuleValidateRequest> filterRuleValidateRequest
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_TwitterApi_H_ */

