/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * VintedApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_VintedApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_VintedApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  VintedApi 
{
public:

    explicit VintedApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~VintedApi();

    /// <summary>
    /// Get item details
    /// </summary>
    /// <remarks>
    /// Get detailed information about a Vinted item.
    /// </remarks>
    /// <param name="itemId"></param>
    /// <param name="market"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> vintedGetItemDetails(
        int32_t itemId,
        boost::optional<utility::string_t> market
    ) const;
    /// <summary>
    /// Get user profile
    /// </summary>
    /// <remarks>
    /// Get a Vinted user&#39;s profile.
    /// </remarks>
    /// <param name="userId"></param>
    /// <param name="market"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> vintedGetUserProfile(
        int32_t userId,
        boost::optional<utility::string_t> market
    ) const;
    /// <summary>
    /// Get user&#39;s listed items
    /// </summary>
    /// <remarks>
    /// Get items listed by a Vinted user.
    /// </remarks>
    /// <param name="userId"></param>
    /// <param name="market"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="perPage"> (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> vintedGetUserSListedItems(
        int32_t userId,
        boost::optional<utility::string_t> market,
        boost::optional<int32_t> page,
        boost::optional<int32_t> perPage
    ) const;
    /// <summary>
    /// List colors
    /// </summary>
    /// <remarks>
    /// Get available Vinted colors for filtering.
    /// </remarks>
    /// <param name="market"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> vintedListColors(
        boost::optional<utility::string_t> market
    ) const;
    /// <summary>
    /// List item conditions
    /// </summary>
    /// <remarks>
    /// Get available item condition statuses.
    /// </remarks>
    /// <param name="market"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> vintedListItemConditions(
        boost::optional<utility::string_t> market
    ) const;
    /// <summary>
    /// List markets
    /// </summary>
    /// <remarks>
    /// List all supported Vinted markets.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> vintedListMarkets(
    ) const;
    /// <summary>
    /// Search brands
    /// </summary>
    /// <remarks>
    /// Search Vinted brands.
    /// </remarks>
    /// <param name="keyword">Brand search keyword</param>
    /// <param name="market"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> vintedSearchBrands(
        utility::string_t keyword,
        boost::optional<utility::string_t> market
    ) const;
    /// <summary>
    /// Search Vinted items
    /// </summary>
    /// <remarks>
    /// Search Vinted catalog items with filters.
    /// </remarks>
    /// <param name="query">Search text</param>
    /// <param name="market">Market code (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sellerCountry">Filter to items whose seller is physically located in one of these comma-separated ISO-2 country codes (e.g. &#39;fr&#39; or &#39;fr,be&#39;). Market domains federate cross-border EU listings and Vinted has no native country filter, so each item is enriched with its seller&#39;s country and non-matching ones are dropped. Adds 1 credit per uncached seller looked up (cached for 7 days). (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="perPage"> (optional, default to 0)</param>
    /// <param name="priceFrom"> (optional, default to 0.0)</param>
    /// <param name="priceTo"> (optional, default to 0.0)</param>
    /// <param name="brandIds"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="catalogIds">Comma-separated Vinted catalog (category) IDs to restrict the search to, e.g. &#39;1904&#39; or &#39;1904,79&#39;. Vinted applies this before searching, so pagination totals reflect the filtered set. A catalog ID is the &#x60;catalog[]&#x60; value in a Vinted category URL (vinted.fr/catalog?catalog[]&#x3D;1904). (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="colorIds">Comma-separated color IDs (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="statusIds">Comma-separated condition/status IDs (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="order"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> vintedSearchVintedItems(
        utility::string_t query,
        boost::optional<utility::string_t> market,
        boost::optional<utility::string_t> sellerCountry,
        boost::optional<int32_t> page,
        boost::optional<int32_t> perPage,
        boost::optional<double> priceFrom,
        boost::optional<double> priceTo,
        boost::optional<utility::string_t> brandIds,
        boost::optional<utility::string_t> catalogIds,
        boost::optional<utility::string_t> colorIds,
        boost::optional<utility::string_t> statusIds,
        boost::optional<utility::string_t> order
    ) const;
    /// <summary>
    /// Vinted scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Vinted scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> vintedVintedScraperHealthCheck(
    ) const;
    /// <summary>
    /// Vinted scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Vinted scraper service.  Accepts &#x60;&#x60;HEAD&#x60;&#x60; so external uptime checkers (UptimeRobot uses HEAD by default for HTTP monitors) don&#39;t get a 405 Method Not Allowed.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> vintedVintedScraperHealthCheckHead(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_VintedApi_H_ */

