/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * YahooApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_YahooApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_YahooApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  YahooApi 
{
public:

    explicit YahooApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~YahooApi();

    /// <summary>
    /// Image search
    /// </summary>
    /// <remarks>
    /// Yahoo Images — thumbnail, full-size and source URL per result.
    /// </remarks>
    /// <param name="query">Search keywords, e.g. &#39;golden retriever&#39;</param>
    /// <param name="market">Yahoo market code, e.g. &#39;us&#39;, &#39;uk&#39;, &#39;fr&#39;, &#39;de&#39;. See /markets. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="count">Results to return (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> yahooImageSearch(
        utility::string_t query,
        boost::optional<utility::string_t> market,
        boost::optional<int32_t> count
    ) const;
    /// <summary>
    /// List supported markets
    /// </summary>
    /// <remarks>
    /// Supported Yahoo market codes. Free — costs no credits.
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> yahooListSupportedMarkets(
    ) const;
    /// <summary>
    /// News search
    /// </summary>
    /// <remarks>
    /// Yahoo News — headline, source, published time and snippet per article.
    /// </remarks>
    /// <param name="query">Search keywords, e.g. &#39;interest rates&#39;</param>
    /// <param name="market">Yahoo market code, e.g. &#39;us&#39;, &#39;uk&#39;, &#39;fr&#39;, &#39;de&#39;. See /markets. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> yahooNewsSearch(
        utility::string_t query,
        boost::optional<utility::string_t> market
    ) const;
    /// <summary>
    /// Search suggestions
    /// </summary>
    /// <remarks>
    /// Yahoo search-box query suggestions.
    /// </remarks>
    /// <param name="query">Partial search term, e.g. &#39;coff&#39;</param>
    /// <param name="market">Yahoo market code, e.g. &#39;us&#39;, &#39;uk&#39;, &#39;fr&#39;, &#39;de&#39;. See /markets. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> yahooSearchSuggestions(
        utility::string_t query,
        boost::optional<utility::string_t> market
    ) const;
    /// <summary>
    /// Video search
    /// </summary>
    /// <remarks>
    /// Yahoo Videos — title, thumbnail, duration, publisher and source per result.
    /// </remarks>
    /// <param name="query">Search keywords, e.g. &#39;espresso tutorial&#39;</param>
    /// <param name="market">Yahoo market code, e.g. &#39;us&#39;, &#39;uk&#39;, &#39;fr&#39;, &#39;de&#39;. See /markets. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="count">Results to return (optional, default to 0)</param>
    pplx::task<std::shared_ptr<AnyType>> yahooVideoSearch(
        utility::string_t query,
        boost::optional<utility::string_t> market,
        boost::optional<int32_t> count
    ) const;
    /// <summary>
    /// Web search
    /// </summary>
    /// <remarks>
    /// Yahoo web SERP — organic results, ads, related searches and total count.
    /// </remarks>
    /// <param name="query">Search keywords, e.g. &#39;coffee machine&#39;</param>
    /// <param name="market">Yahoo market code, e.g. &#39;us&#39;, &#39;uk&#39;, &#39;fr&#39;, &#39;de&#39;. See /markets. (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="offset">Zero-based result offset for pagination (optional, default to 0)</param>
    /// <param name="safeSearch">off | moderate | strict (default moderate) (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> yahooWebSearch(
        utility::string_t query,
        boost::optional<utility::string_t> market,
        boost::optional<int32_t> offset,
        boost::optional<utility::string_t> safeSearch
    ) const;
    /// <summary>
    /// Yahoo scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Yahoo scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> yahooYahooScraperHealthCheck(
    ) const;
    /// <summary>
    /// Yahoo scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Yahoo scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> yahooYahooScraperHealthCheckHead(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_YahooApi_H_ */

