/**
 * ScrapeBadger API
 * Unified credit-based scraping API. https://docs.scrapebadger.com
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ZillowApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ZillowApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ZillowApi_H_



#include "scrapebadger/ApiClient.h"

#include "scrapebadger/AnyType.h"
#include "scrapebadger/model/HTTPValidationError.h"
#include <cpprest/details/basic_types.h>
#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ZillowApi 
{
public:

    explicit ZillowApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ZillowApi();

    /// <summary>
    /// Get agent profile + listings
    /// </summary>
    /// <remarks>
    /// Get a Zillow professional&#39;s profile and their active listings.
    /// </remarks>
    /// <param name="username">Zillow profile username (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="url">Full Zillow /profile/... URL (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<AnyType>> zillowGetAgentProfileListings(
        boost::optional<utility::string_t> username,
        boost::optional<utility::string_t> url
    ) const;
    /// <summary>
    /// Get property detail
    /// </summary>
    /// <remarks>
    /// Get a single Zillow property&#39;s full detail by zpid.
    /// </remarks>
    /// <param name="zpid"></param>
    pplx::task<std::shared_ptr<AnyType>> zillowGetPropertyDetail(
        utility::string_t zpid
    ) const;
    /// <summary>
    /// Get property detail by URL
    /// </summary>
    /// <remarks>
    /// Get a single Zillow property&#39;s full detail by its homedetails URL.
    /// </remarks>
    /// <param name="url">Full Zillow /homedetails/... URL</param>
    pplx::task<std::shared_ptr<AnyType>> zillowGetPropertyDetailByUrl(
        utility::string_t url
    ) const;
    /// <summary>
    /// List coverage markets
    /// </summary>
    /// <remarks>
    /// List Zillow coverage regions (US + Canada).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> zillowListCoverageMarkets(
    ) const;
    /// <summary>
    /// Region/address suggestions
    /// </summary>
    /// <remarks>
    /// Resolve a search term to Zillow regions/addresses.
    /// </remarks>
    /// <param name="query">Partial location — city, ZIP, address, neighborhood</param>
    pplx::task<std::shared_ptr<AnyType>> zillowRegionAddressSuggestions(
        utility::string_t query
    ) const;
    /// <summary>
    /// Search properties
    /// </summary>
    /// <remarks>
    /// Search Zillow for for-sale / for-rent / recently-sold properties.
    /// </remarks>
    /// <param name="location">City/state, ZIP, address or neighborhood</param>
    /// <param name="status">for_sale|for_rent|sold (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="page"> (optional, default to 0)</param>
    /// <param name="sort">homes_for_you|newest|price_high_to_low|price_low_to_high|bedrooms|bathrooms|square_feet|lot_size|year_built (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="priceMin"> (optional, default to 0)</param>
    /// <param name="priceMax"> (optional, default to 0)</param>
    /// <param name="bedsMin"> (optional, default to 0)</param>
    /// <param name="bathsMin"> (optional, default to 0.0)</param>
    /// <param name="homeType">houses|condos|townhomes|apartments|manufactured|lots|multi_family (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="sqftMin"> (optional, default to 0)</param>
    /// <param name="sqftMax"> (optional, default to 0)</param>
    /// <param name="lotMin"> (optional, default to 0)</param>
    /// <param name="lotMax"> (optional, default to 0)</param>
    /// <param name="yearBuiltMin"> (optional, default to 0)</param>
    /// <param name="yearBuiltMax"> (optional, default to 0)</param>
    /// <param name="hoaMax"> (optional, default to 0)</param>
    /// <param name="keywords"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="daysOn"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    /// <param name="north">Map bounds for tiling past the 820 cap (optional, default to 0.0)</param>
    /// <param name="south"> (optional, default to 0.0)</param>
    /// <param name="east"> (optional, default to 0.0)</param>
    /// <param name="west"> (optional, default to 0.0)</param>
    pplx::task<std::shared_ptr<AnyType>> zillowSearchProperties(
        utility::string_t location,
        boost::optional<utility::string_t> status,
        boost::optional<int32_t> page,
        boost::optional<utility::string_t> sort,
        boost::optional<int32_t> priceMin,
        boost::optional<int32_t> priceMax,
        boost::optional<int32_t> bedsMin,
        boost::optional<double> bathsMin,
        boost::optional<utility::string_t> homeType,
        boost::optional<int32_t> sqftMin,
        boost::optional<int32_t> sqftMax,
        boost::optional<int32_t> lotMin,
        boost::optional<int32_t> lotMax,
        boost::optional<int32_t> yearBuiltMin,
        boost::optional<int32_t> yearBuiltMax,
        boost::optional<int32_t> hoaMax,
        boost::optional<utility::string_t> keywords,
        boost::optional<utility::string_t> daysOn,
        boost::optional<double> north,
        boost::optional<double> south,
        boost::optional<double> east,
        boost::optional<double> west
    ) const;
    /// <summary>
    /// Zillow scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Zillow scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> zillowZillowScraperHealthCheck(
    ) const;
    /// <summary>
    /// Zillow scraper health check
    /// </summary>
    /// <remarks>
    /// Check health of the Zillow scraper service (accepts HEAD for UptimeRobot).
    /// </remarks>
    pplx::task<std::shared_ptr<AnyType>> zillowZillowScraperHealthCheckHead(
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ZillowApi_H_ */

